### ISSUE TITLE
Feature Request :: Nested URLs without Nesting Layouts

### ISSUE THREAD

**Issue by davemo** [oedotme/generouted#10]
Having support for convention-based nested URLs while being able to escape from the default layout convention in a given folder would be awesome. 😄 

As per the remix.run docs: https://remix.run/docs/en/v1/guides/routing#nested-urls-without-nesting-layouts

> So, if we want a flat UI hierarchy, we create a flat filename--we use "." to create segments instead of folders. This defines URL nesting without creating component nesting.

```
└── app
    ├── root.jsx
    └── routes
        ├── sales
        │   ├── invoices
        │   │   └── $invoiceId.jsx
        │   └── invoices.jsx
        ├── sales.invoices.$invoiceId.edit.jsx 👈 not nested
        └── sales.jsx
```

> Just for absolute clarity, if the url is "example.com/sales/invoices/2000/edit", we'll get this UI hierarchy that matches the file system hierarchy:

```jsx
<Root>
  <EditInvoice />
</Root>
```

**Comment by oedotme** [comment]
Hey @davemo, this is already supported. It's on the readme/docs but it might not be super obvious 😄 https://github.com/oedotme/generouted#exclude-a-route---url-nesting-without-layout-nesting

**Comment by davemo** [comment]
Awesome! Thanks for pointing that out, I definitely missed it 😅

**Comment by davemo** [comment]
Oh, one thing I wondered @oedotme  is if generouted supports this paradigm along with route params? ie:

`sales.invoices.[invoice_id].edit.tsx` ?

**Comment by oedotme** [comment]
Yup, that's supported with multiple params as well, thanks to @bzbetty. Here's an example:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/20151138/197008219-fa97338b-e83e-40b0-8078-5c1c28a1cdca.png">

**Comment by davemo** [comment]
Thank you for the examples! ❤️

**Comment by davemo** [comment]
Ok, I think I figured out what my issue is. If the un-nested route you want to add happens to start with the same name as a nested route segment then the ordering of the react-location route matches doesn't work to render the nested layout.

Here's an example of what I'm seeing with the following folder structure:

![Screen Shot 2022-10-20 at 5 21 44 PM](https://user-images.githubusercontent.com/69559/197061148-8e4b50f8-8f6d-401b-9e3d-30f14b021d12.png)

The nested `companies.[cid].offer_letters.[oid].edit.tsx` filename isn't rendered because `companies.[cid]` seems to be matched first:

![Screen Shot 2022-10-20 at 5 22 44 PM](https://user-images.githubusercontent.com/69559/197061338-3b41b9fe-80a9-441f-819e-eea92fb9312b.png)

However, it does work with the posts example you provided:

![Screen Shot 2022-10-20 at 5 22 25 PM](https://user-images.githubusercontent.com/69559/197061251-59c77b2e-b39b-4d6d-ac28-86b0d4caf128.png)

I'm wondering if this is just an ordering bug and generouted should move unnested files to the top of the route-resolution object @oedotme ?

**Comment by oedotme** [comment]
@davemo I think the issue is exactly as you described, at the nested routes order. Will take a look at it. Thank you!

**Comment by davemo** [comment]
👍
