### ISSUE TITLE
Uncaught Error: useNavigate() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by masafumimori** [oedotme/generouted#101]
### Describe the Bug

First of all, this library is amazing! Thanks for that.

This is not a bug but I couldn't figure out how to fix this so I post this here.

I have auth context with `useNavigate` function used inside. (like when logged out, navigate to home page etc)
But since its provider is outside of the `<Routes/>` from this library, it gives me an error in the title.

```javascript
// main.tsx
ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <AuthProvider>
      <Routes />
    </AuthProvider>
  </React.StrictMode>
);
```

Is there a way to make this work? rather than adding AuthProvider to each components under `pages` directory?

### Generouted Version

1.15.1

### Your Example Website or App or Reproduction

not available

### Steps to Reproduce the Bug or Issue

1. create a context
2. wrap Routes with the context provider
```javascript
import { createContext, useState } from 'react';
import { useNavigate } from 'react-router-dom';

const initialAuthContext = {
  user: '',
  logout: () => undefined
};

export const AuthContext = createContext<{ user: string; logout: () => void }>(
  initialAuthContext
);

export const AuthProvider: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => {
  const [user, setUser] = useState<string>(''); // to be simple
  const navigate = useNavigate();

  const logout = async () => {
    // code to logout...
    navigate('/');
  };

// some other codes...

  return (
    <AuthContext.Provider value={{ user, logout }}>
      {children}
    </AuthContext.Provider>
  );
};
```

### Expected Behavior

Hopefully i can use provider with navigate

### Platform

- OS: macOS
- Browser: Chrome

**Comment by sohaibaumer** [comment]
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';

ReactDOM.render(
  <React.StrictMode>
    <Router>
      <AuthProvider>
        <Routes>
          {/* Your routes go here */}
        </Routes>
      </AuthProvider>
    </Router>
  </React.StrictMode>,
  document.getElementById('root')
);

By wrapping the AuthProvider within the Router component, you ensure that the useNavigate hook has access to the router's navigation.

**Comment by masafumimori** [comment]
@sohaibaumer 
Thank you for your answer!

So basically, I cannot use Routes from `@generouted/react-router`?

I'm sorry I was meant to put this code as well:
```jasvascript
// in main.tsx
import React from 'react';
import { Routes } from '@generouted/react-router';
import ReactDOM from 'react-dom/client';
import { AuthProvider } from './context/auth';

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <AuthProvider>
        <Routes />
    </AuthProvider>
  </React.StrictMode>
);
```

**Comment by sohaibaumer** [comment]
You can! Pass the navigate function returned by useNavigate hook as part of the auth context, that way it will be available in the auth context and you can use it in you in any of your auth consumers.

**Comment by oedotme** [comment]
Hey @masafumimori, thanks for your comment. I usually place the auth/redirects provider at `src/pages/_app.tsx` as that's the app layout and its within the router context. Check https://github.com/oedotme/render/blob/main/src/pages/_app.tsx and the [`render` template repo](https://github.com/oedotme/render) for a full example. For a minimal example, it should be something like that:

```tsx
// src/pages/_app.tsx

import { Outlet } from 'react-router-dom'

import { AuthProvider } from '@/context'

export default function App() {
  return (
    <AuthProvider>
      <Outlet />
    </AuthProvider>
  )
}
```

Hope that helps!

**Comment by masafumimori** [comment]
@oedotme 
Wow!! That solved the issue!!
Thank you so much!
