### ISSUE TITLE
New routes not discovered on Windows

### ISSUE THREAD

**Issue by bcallar** [oedotme/generouted#104]
### Describe the Bug

Hi,

I'm using Generouted with react-js using Vite bundler, **on Windows**.
When I add a new route into my app folder, the new route is not discovered automaticaly and I have to reload vite server.
This is an issue because when I reload the link between the browser and vite for HMR is closed and I have to reload my browser also.

I have tried on other desktop using Linux Ubuntu : no issue. I have tried on other Windows computer : same issue.

### Generouted Version

1.15.1

### Your Example Website or App or Reproduction

https://stackblitz.com/github/oedotme/generouted/tree/main/examples/react-router?file=readme.md

### Steps to Reproduce the Bug or Issue

1. Clone the github on Windows
2. npm install
3. npm run dev
4. Create new route : the new route is not discovered
5. Reload Vite by pressing "r" button : The route is discovered

### Expected Behavior

The route should be discovered automatically like it does on Linux

### Platform

- OS: Windows 10 (also tested on 11)
- Browser: Chrome
- Browser version: 114

**Comment by oedotme** [comment]
Hey @bcallar, thanks for reporting this.

I recall encountering this issue in a project on Windows without using `generouted`. In fact `generouted` uses Vite APIs directly to scan the modules, and any change in the modules is handled by Vite and its HMR as well.

Please open an issue at [Vite's repo](https://github.com/vitejs/vite) if there's no already.

**Comment by oedotme** [comment]
@bcallar there's a related PR #108 that fixes the pages detection by the types plugin. I don't expect it to fix the issue you described here entirely, but please give it a try at [v1.15.3](https://github.com/oedotme/generouted/releases/tag/v1.15.3) and let me know.

**Comment by bcallar** [comment]
Hi !
Thank you for this news ! And thanks to @agustinbravop for this PR.
I tested and it is much better ! All routes added/deleted are discovered automatically. You can close this issue.
Regards

**Comment by oedotme** [comment]
Awesome, thanks for the update!
