### ISSUE TITLE
help : how to give props to page from layout using Outlet component

### ISSUE THREAD

**Issue by bcallar** [oedotme/generouted#106]
Hi,
Thank you for your package that is very usefull and simple to use.

I need to give props from layout to generated page (using **<Outlet />**).

I tried to give like usually **<Outlet name='test' />** and from my page, use this props : **export default function MyPage({props})** or **export default function MyPage(props)** but it is always undefined or empty.

Am I missing something ?
My final purpose is to change a layout content (header) depending of the generated page, so I want to pass the useState discard function using props.

Thank you for your help

**Comment by bcallar** [comment]
Sorry, you can delete this issue, I found by myself using the useOutletContext hook from react-dom-router.

**Comment by oedotme** [comment]
Hey @bcallar, thanks your comment.

Thanks for sharing your findings, I wasn't aware of the `useOutletContext` hook.
