### ISSUE TITLE
feat: react router support

### ISSUE THREAD

**Issue by oedotme** [oedotme/generouted#11]
Support [`react-router-dom`](https://reactrouter.com/en/main):

- Same `generouted` routing conventions w/ nested layouts
- Route-based loader
- Route-based action

**Comment by andrioid** [comment]
That would be cool, but probably requires some sort of plugin system.

I was browsing [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) and was missing "loaders" to fully utilize React Router when I found your project. Delightful to see it "just work" with import.meta.glob without any need for plugins.

vite-plugin-pages has an OK "[resolver](https://github.com/hannoeru/vite-plugin-pages/blob/main/src/types.ts#L28)" interface to support multiple routers; but its' support for multiple "router style" makes the plugins hard to reason about.

So all I wanted to say, is that if you decide to make the router generation flexible; consider to create solid abstractions for both the route-style and the router-resolver so you don't end up with the same amount of `if routerstyle` .

**Comment by oedotme** [comment]
Thanks for the suggestions! As I recently added React Router support (still not released) I did something similar to what you're suggesting. Seems to work well so far and it supports route-based loader and action functions.

I expect it to work for Solid and other possible integrations as well.

Would love to hear what you think once it's released ;)

**Comment by andrioid** [comment]
I’d be happy to review it

**Comment by oedotme** [comment]
Thanks! Although it's not yet released, I did push some updates related to multiple routers support (`react-location` and `react-router`), you can find the core and the two integrations at the [src](https://github.com/oedotme/generouted/blob/main/src) directory:

```shell
src/
├── core.ts
├── react-location.tsx
└── react-router.tsx
```

A new release should include that soon, after some required docs updates.

**Comment by andrioid** [comment]
Looks good so far, but isn't it missing the `<Route>` component? At least it felt like there was some code missing. Do you have a PR somewhere for the upcoming release?

**Comment by oedotme** [comment]
The exported `Routes` component can be found in each integration file at `src/react-location.tsx` and `src/react-router.tsx`.

All latest updates (except docs) were already pushed to the main branch, you can find the file-based routes core/config at `src/core.ts`.

The core exports two functions to generate the routes and the preserved routes, and used in the current (and upcoming) integrations.
