### ISSUE TITLE
The issue of passing useState values in the _layout.tsx file

### ISSUE THREAD

**Issue by tomatoword** [oedotme/generouted#112]
Hello. I would like to ask. I used generouted file routing, and then in my _ layout. tsx file, I used React. useState() to store data. And then I created a new folder called newNode in the same level directory as the layout.tsx file, and then created the file index.tsx in the new folder. May I obtain the data values stored in _layout. tsx from index. tsx. thanks

**Comment by oedotme** [comment]
Hey @tomatoword, you can use [`useOutletContext`](https://reactrouter.com/en/main/hooks/use-outlet-context) to pass state and other values from the `_layout.tsx` to its children.

I've discovered this hook from #106. Hope that helps!

**Comment by tomatoword** [comment]
thanks
