### ISSUE TITLE
Global Modal opens in current route

### ISSUE THREAD

**Issue by AndriiPavlykivskyi** [oedotme/generouted#116]
Hi, I have page `general` with modal `details`

```
export type Path = `/` | `/general` | `/table`;

export type Params = {};

export type ModalPath = `/general/details`;
```

When I try to open the modal being at the `/general` 
`<Button onClick={() => modals.open('/general/details')}>Link to details</Button>`
page it opens up, but location doesn't change. Also I can't reach the modal by `/general/details` path;
![image](https://github.com/oedotme/generouted/assets/91653412/097b03ab-4adf-4185-a521-eef9f067c57d)

Version of @generouted/react-router: 1.15.4

**Comment by archiekd** [comment]
@AndriiPavlykivskyi Did you solve this? I am having the same issue

**Comment by oedotme** [comment]
Hey @archiekd, #117 has more info about the same question. Here's a quick explanation https://github.com/oedotme/generouted/issues/117#issuecomment-1682369841

Hope that help!
