### ISSUE TITLE
Modal opens in current path, not the specified

### ISSUE THREAD

**Issue by AndriiPavlykivskyi** [oedotme/generouted#117]
Hi, I have page `general` with modal `details` in it

```
export type Path = `/` | `/general`;

export type Params = {};

export type ModalPath = `/general/details`;
```

When I try to open the modal being at the `/general`  clicking on button
`<Button onClick={() => modals.open('/general/details')}>Link to details</Button>`
modal opens up, but location doesn't change. Also I can't reach the modal by `/general/details` path;

![image](https://github.com/oedotme/generouted/assets/91653412/097b03ab-4adf-4185-a521-eef9f067c57d)
![image](https://github.com/oedotme/generouted/assets/91653412/e86a973f-3c6b-4a66-acd3-8e666cd02fad)
![image](https://github.com/oedotme/generouted/assets/91653412/ea9901f5-f6cb-4362-8fec-ea272970bb43)

Version of @generouted/react-router: 1.15.4

**Comment by AndriiPavlykivskyi** [comment]
Many thanks for your explanation. 

I've read the docs section about modals https://github.com/oedotme/generouted#global-modals and I thought I can reach the modal `src/pages/+info.tsx` by path `/info`. Seems clear for me know, thanks.

**Comment by oedotme** [comment]
Glad to hear that! You could also find more information about the modals at [`react-router-dom` integration docs](https://github.com/oedotme/generouted/tree/main/plugins/react-router#type-safe-global-modals).
