### ISSUE TITLE
Webpack plugin

### ISSUE THREAD

**Issue by d0whc3r** [oedotme/generouted#128]
Any possibility to make it webpack compatible?

**Comment by oedotme** [comment]
It's possible AFAIK — but not necessarly compatible. Like that would need `webpack` implementation for the runtime integrations with its APIs equivalent to Vite's `import.meta.glob`. Also `webpack` plugins per integration for types generation.

TBH, I started `generouted` to be Vite-based project and was not planning to support other bundlers with their APIs differences, plugin system, etc. That may change on the long-term though.
