### ISSUE TITLE
feat!: move layout route inside directory

### ISSUE THREAD

**Issue by bzbetty** [oedotme/generouted#13]
Any thoughts on implementing something like this?

https://github.com/expo/router/pull/89

**Comment by oedotme** [comment]
There are couple of concerns about the new Expo's router:
- It would make possible to have `pages/posts.tsx` and `pages/posts/index.tsx` - so would be conflicting/confusing
- It would require a sorting/ranking mechanism as `_layout.tsx` wouldn't be always on top - w/ dynamic routes
- It would be less similar to Remix

The only advantage I see is the ability to group the layout file with its related routes.

**Comment by bzbetty** [comment]
* It would make possible to have pages/posts.tsx and pages/posts/index.tsx - so would be conflicting/confusing

I'd argue that you'd want to support both models where the render order would nest

 pages/posts.tsx >  pages/_layout.tsx >  pages/posts/index.tsx

which i guess would basically lead to supporting remixes pathless layouts

Whether you'd ever need both at the sametime I have no idea.

* It would require a sorting/ranking mechanism as _layout.tsx wouldn't be always on top - w/ dynamic routes

yeah the sorting thing would be a bit of a pain seeing as _ comes after [ in ascii, i do like how little code this library is compared to pretty much every other one.

* It would be less similar to Remix

interesting, I thought you followed next.js more than remix

**other notes**

it would add a nice convention to replace the built in rule for the _app file.

side note: would a [...all] work for a 404 page?

**Comment by oedotme** [comment]
> I'd argue that you'd want to support both models where the render order would nest
> `pages/_layout.tsx > pages/posts.tsx > pages/posts/_layout.tsx > pages/posts/index.tsx`

I thought of adding `.layout.tsx` to the layout file would keep current keep the current implementation as is and will make it more clear which is the layout file, what do you think?

```shell
pages
├── about.tsx
├── index.tsx
├── posts.layout.tsx
└── posts
    ├── [slug].tsx
    └── index.tsx
```
Basically it would be only to indicate the layout for readability but wouldn't change how it works now. I still find it nice to have the layout file outside of the nested routes. 

Thanks for sharing about pathless routes! the first time I hear about it.

<br>

> - It would be less similar to Remix
> interesting, I thought you followed next.js more than remix

It's correct, `generouted` is more inspired by Next.js (before the new router), but because nested layouts were Remix specific initially, I did mention that point ;)

<br>

> it would add a nice convention to replace the built in rule for the _app file.

You mean renaming `_app.tsx` to `_layout.tsx`? It does make sense, specially after the Next.js new router update.

<br>

> side note: would a [...all] work for a 404 page?

I guess that's how it works now.

**Comment by bzbetty** [comment]
A .layout.tsx would be a nice addition.

my issue is potentially that my editor groups folders before files, so any layout file is generally quite a distance from the related files, it's a big reason I prefer the _layout.tsx files idea.

For now I've ended up deviating from using generouted modifying it to work how I want. Haven't done a lot of testing to see what it breaks, although I have also broken it into two files (one to calculate routes and another to integrate with react location) which I think would make it more testable, so maybe I will.

I'll paste it in here later for reference if anyone else is interested

**Comment by bzbetty** [comment]
```
import React, { Fragment } from 'react'
import { LoaderFn, Route } from '@tanstack/react-location'

type Module = { default: () => JSX.Element; loader: LoaderFn }

function getRoutes(ROUTES: { [key: string]: () => Promise<Module> }) {
  return Object.keys(ROUTES).reduce<Route[]>((routes, key) => {
    const module = ROUTES[key];
    const route: Route = {
      element: () => module().then((mod) => (mod?.default ? <mod.default /> : <></>)),
      loader: (...args) => module().then((mod) => mod?.loader?.(...args)),
    }

    const segments = key
        .replace(/\[\.{3}.+\]/, '*')
        .replace(/\[([^\]]+)\]/g, ':$1')
        .split('/')        

    segments.reduce((parent, segment, index) => {
      const path = segment.replace(/index|\./g, '/').replace("_", "")
      const root = index === 0 || segment.startsWith('_');
      const leaf = index === segments.length - 1 && segments.length > 1
      const node = !root && !leaf
      const insert = /^\w|\//.test(path) ? 'unshift' : 'push'
      
      if (root) {
        const dynamic = path.startsWith(':') || path === '*'
        if (dynamic) return parent

        const last = segments.length === 1 || segment.startsWith('_');
        if (last) {         
          routes.push({ path, ...route })
          return parent
        }
      }

      if (root || node) {
        const current = root ? routes : parent.children
        const found = current?.find((route) => route.path === path)
        if (found) found.children ??= []
        else current?.[insert]({ path, children: [] })
        return found || (current?.[insert === 'unshift' ? 0 : current.length - 1] as Route)
      }

      if (leaf) {
        const found = parent?.children?.find((route) => route.path === path) 
        if(!found) {
          parent?.children?.[insert]({ path, ...route })
        } else {
          Object.assign(found, route);
        }
      }

      return parent
    }, {} as Route)

    return routes
  }, [])
};

// @ts-ignore
let PAGES = import.meta.glob('../pages/**/[_a-z[]*.tsx');

PAGES = Object.fromEntries(
  Object.entries(PAGES).map(([key, value]) => 
    [
      key
        .replace(/..\/pages|\.tsx$/g, '')
        .replace('/_layout', ''),
      value
    ]
  )
)

export default {
  pages: getRoutes(PAGES)
}

```

**Comment by oedotme** [comment]
Thanks a lot for providing the code. I recently also broke down the source code into `core` and `integrations`, now it looks something like that:

```shell
src/
├── core.ts
├── react-location.tsx
└── react-router.tsx
```

Here's the change based on the snippet you provided to support nested `_layout.tsx` https://github.com/oedotme/generouted/commit/3e0ae764d94cbe23043e18ab63a764904eba2a0c.

The existing layout definition is still there as well, so `pages/posts.tsx` or `pages/posts/_layout.tsx` are valid layouts but only one should be used. In case both are present, `_layout.tsx` will be the layout used.

I'll close this issue once released a new version after some docs updates.
