### ISSUE TITLE
Route problem

### ISSUE THREAD

**Issue by zeeeeby** [oedotme/generouted#130]
Hello, I have this directory tree
<img width="212" alt="image" src="https://github.com/oedotme/generouted/assets/44382546/50b6a4e5-24d9-467e-9529-958e4f50264c">

 i expect, that path `/pub/dashboard` matches file `[...all].tsx`, but it dont match neither `/pub/:id/dashboard` nor `/pub/*  `
 I didnt understand why.
Can you please help?

**Comment by oedotme** [comment]
Glad to see it was solved. 

Wanted to highlight that in your example, you could use optional segment to match the two urls you've mentioned without using `[...all].tsx` as a wildcard route.

Having `src/pages/pub/-[id]/dashboard.tsx` instead, would resolve to `/pub/:id?/dashboard` which matches both `/pub/:id/dashboard` and `/pub/dashboard`.

Hope that helps!
