### ISSUE TITLE
[Feature] React "Catch" with error information

### ISSUE THREAD

**Issue by WildEgo** [oedotme/generouted#136]
Hi, amazing library.

I saw that Solid has error information on the "Catch" component, it would be nice to also have it on React for error reporting and the sorts.

**Comment by oedotme** [comment]
@WildEgo Thanks for your comment!

You can access the `error` information by using the [`useRouteError`](https://reactrouter.com/en/main/hooks/use-route-error) hook within the exported `Catch` component.

You can also have a [custom integration for React Router](https://github.com/oedotme/generouted/tree/main/examples/react-router-custom) and expose it the same way as Solid Router.
