### ISSUE TITLE
Feature Request: Programmatically Handling Routes

### ISSUE THREAD

**Issue by mooxl** [oedotme/generouted#138]
### Current State:
Currently, generouted uses ﻿Path as a TypeScript ﻿type, which is a union of string literals. This setup inhibits the capacity to programmatically filter paths, as types cannot be iterated over.
```ts
export type Path =
  | `/`
  | `/login`
  | `/login/create`
  | `/tickets`
```

### Feature Request:
The feature proposal is to refactor ﻿Path into a constant array. This allows developers to use array methods like ﻿filter and ﻿map for more flexibility.
```ts
export const Paths = [
  `/`,
  `/importerPipelines`,
  `/importerPipelines/create`,
  `/login`,
  `/login/create`,
  `/tickets`,
] as const;

export type Path = (typeof Paths)[number];
```

This alteration significantly simplifies the method of implementing the Redirect Pattern of [Render](https://github.com/oedotme/render) . It eases managing 'protected' and 'public' routes since developers can now programmatically filter the public routes.

**Comment by evanlong0926** [comment]
Yes, I added the 'components' directory in the same way, but it shouldn't have been scanned.

**Comment by collins401** [comment]
> Yes, I added the 'components' directory in the same way, but it shouldn't have been scanned.
> 
> ![image](https://private-user-images.githubusercontent.com/52912949/283998040-75bcaeee-418e-47d0-a419-13fe95f6202b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE2MzYsIm5iZiI6MTcwMjAwMTMzNiwicGF0aCI6Ii81MjkxMjk0OS8yODM5OTgwNDAtNzViY2FlZWUtNDE4ZS00N2QwLWE0MTktMTNmZTk1ZjYyMDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDYyNjRlYTM0MGY4YTdkNzI3NTUxNWI2MGJmZjhhMTgzMGIwYjg4OGQ1YWQ0MDRkZjE3YmY5ODk0MDQ5NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xf6lwbkmOD7IfaJWhA5MxbKgpO8g0uIKPm_1cfyj5rs)
> 
> ![image](https://private-user-images.githubusercontent.com/52912949/283998051-e76095d0-165c-48de-9414-ca9f22b19060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDE2MzYsIm5iZiI6MTcwMjAwMTMzNiwicGF0aCI6Ii81MjkxMjk0OS8yODM5OTgwNTEtZTc2MDk1ZDAtMTY1Yy00OGRlLTk0MTQtY2E5ZjIyYjE5MDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMTFlN2UwOTNiOTA3ZmFmOWE0MzE3MjY4ODVkMTYxOTg0NjE4NWRiZTZhMDkzZmZhM2Q4Nzc3MGQxZTUzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ENcYo-w_j2aZqUSwtsnP2kDluKZ4YbwbPEIOodZyEvc)

try it
```
// vite.config.ts
generouted({
    source: {
      routes: ['./src/pages/**/[\\w[-]*.{jsx,tsx}', '!./src/pages/**/components/**'],
      modals: './src/pages/**/[+]*.{jsx,tsx}'
    }
  }),
```

**Comment by oedotme** [comment]
@mooxl unfortunately the generated file is intentionally meant only for types. Using runtime exports either for routes declaration and other exports were causing specific issue with Vite's HMR.

If you need to have a runtime list of the available routes matching `generouted` at the moment, you could use the same code used to [generate the types](https://github.com/oedotme/generouted/blob/main/packages/react-router/src/plugin/generate.ts#L16-L42): 

```tsx
import { patterns } from '@generouted/react-router/core'

const ROUTES = import.meta.glob(['/src/pages/**/[\\w[-]*.{jsx,tsx}', '!**/(_app|404).*'], { eager: true })

const filtered = Object.keys(ROUTES).filter((key) => !key.includes('/_') && !key.includes('/404'))
const paths = filtered
  .map((key) => {
    const path = key
      .replace(...patterns.route)
      .replace(...patterns.splat)
      .replace(...patterns.param)
      .replace(/\(\w+\)\/|\/?_layout/g, '')
      .replace(/\/?index|\./g, '/')
      .replace(/(\w)\/$/g, '$1')
      .split('/')
      .map((segment) => segment.replace(...patterns.optional))
      .join('/')

    return path.length > 1 ? `/${path}` : path
  })
  .filter(Boolean)

console.log(paths)
// [
//   "/login",
//   "/register",
//   "/about",
//   "/blog/w/o/layout",
//   "/blog/:slug",
//   "/blog",
//   "/blog/tags",
//   "/docs/:lang?",
//   "/docs/:lang?/resources",
//   "/"
// ]

```

This is unlikely to change, I'll let you know if a utility function is exported for the paths transformation. Or in case `router.tsx` started exporting runtime values.

Hope that helps.
