### ISSUE TITLE
Compatibility with Electron?

### ISSUE THREAD

**Issue by user72356** [oedotme/generouted#14]
I'm developing my app for the web first, with the future goal of adding Electron as a compilation target and keeping close to 100% of the code base shared between web and Electron.

With that in mind, I decided to skip Next.js and instead use plain React because it's more easily integrated in Electron. I like your idea of bringing Next.js-inspired routing to plain React!

Before I get too deep into the rabbit hole though, is generouted compatible with an Electron environment as-is? Meaning no code changes or adaptations are required.

**Comment by oedotme** [comment]
From what I understand, Electron has no issues with the routing you choose, eventually you're writing a React application. But I recall it requires a hash-based router.

One simple thing that I was planning to do for other/upcoming integrations as well, is to export the `routes` object, then it can be reused in any other customized way.

This following code wouldn't work as of now, just to illustrate the use with the current React Location integration:
```tsx
import { createHashHistory, ReactLocation, Router } from '@tanstack/react-location'
import { routes } from 'generouted'
 
const history = createHashHistory()
const location = new ReactLocation({ history })

const App = ()=> {
  return <Router location={location} routes={routes} />
}
```

Also you'll be able to use React Router hash router for that, once the `react-router` integration is added to `generouted`.

**Comment by chiqors** [comment]
> react-router

would you explain how to implement this with react-router-dom v6? sorry i am new into this

**Comment by chiqors** [comment]
> react-router

@oedotme would you explain how to implement this with react-router-dom v6? sorry i am new into this

**Comment by oedotme** [comment]
Hey @chiqors, `react-router-dom` supports hash routers which is a kind of router that's used for environment like `electron`.

You can check `react-router-dom` docs for reference https://reactrouter.com/en/main/routers/create-hash-router to create the hash router. Then you can import the `routes` object from `@generouted/react-router` and pass it to `createHashRouter` to get the file-based routing working as well.

If you're opened to use different technologies to build desktop applications with web technologies, you can check out Tauri https://tauri.app - which seems to work directly with `createBrowserRouter` https://reactrouter.com/en/main/routers/create-browser-router.

Hope that helps!
