### ISSUE TITLE
Feature: Support React Query in React Router

### ISSUE THREAD

**Issue by gunta** [oedotme/generouted#140]
Or optionally:
- let the user configure the route and its context
- let the user configure the template

**Comment by oedotme** [comment]
@gunta AFAIK there's nothing special needed for supporting React Query with React Router through `generouted`.

Here's an article about [React Query + React Router](https://tkdodo.eu/blog/react-query-meets-react-router) covering prefetch and invalidation through `action` and `loader` functions which you can use at `generouted` by exporting route-based `Action`/`Loader` function.

Also you could add a [custom `routes.tsx`](https://github.com/oedotme/generouted/tree/main/examples/react-router-custom) to modify and/or configure more exports, see #103.


Hope that helps.
