### ISSUE TITLE
Custom path not working

### ISSUE THREAD

**Issue by coldagofee** [oedotme/generouted#142]
### default config
it working as expected [stackblitz default config](https://stackblitz.com/edit/vitejs-vite-yh4nic)

router.ts: 
```ts
// Generouted, changes to this file will be overriden
/* eslint-disable */

import { components, hooks } from '@generouted/solid-router/client'

export type Path =
  | `/`
  | `/about`

export type Params = {
  
}

export type ModalPath = never

export const { A, Navigate } = components<Path, Params>()
export const { useMatch, useModals, useNavigate, useParams } = hooks<Path, Params, ModalPath>()

```

### custom path config
i followed this  [example](https://github.com/oedotme/generouted/blob/main/examples/react-router-custom-path/vite.config.ts), but my app just showing blank page. [stackblitz custom config](https://stackblitz.com/edit/vitejs-vite-9hkq5j)

vite.config.ts:
```ts
import { defineConfig } from 'vite';
import solid from 'vite-plugin-solid';
import generouted from '@generouted/solid-router/plugin';

export default defineConfig({
  plugins: [
    solid(),
    generouted({
      source: {
        routes: './src/custom/**/[\\w[-]*.{jsx,tsx}',
        modals: './src/custom/**/[+]*.{jsx,tsx}',
      },
    }),
  ],
});
```

router.ts: 
```ts
// Generouted, changes to this file will be overriden
/* eslint-disable */

import { components, hooks } from '@generouted/solid-router/client'

export type Path =
  | `///src/custom`
  | `///src/custom/about`

export type Params = {
  
}

export type ModalPath = never

export const { A, Navigate } = components<Path, Params>()
export const { useMatch, useModals, useNavigate, useParams } = hooks<Path, Params, ModalPath>()

```

**Comment by oedotme** [comment]
@coldagofee The routes directory should always end with `src/pages` as a convention, this option was introduced for certain projects that requires a certain nested structure as in full stack non-js projects or non-workspace monorepo tooling.

You can replace the config directory with `./some-directory/src/pages/...`, also you'd need to have a custom `./some-directory/src/routes.tsx` similar to [`./client/src/routes.tsx`](https://github.com/oedotme/generouted/blob/main/examples/react-router-custom-path/client/src/routes.tsx) to scan the routes correctly based on the custom path.

**Comment by coldagofee** [comment]
@oedotme oooh thanks for the explaination

**Comment by joshuagraber** [comment]
Hey @oedotme Can I ask, what would I need to do to override the `src/pages` requirement? That seems extremely inflexible to me.

I'm working with a feature-based directory structure (say `src/features/**` and would like to read routes from that entire directory, where each child of `src/features` is the base route of a feature. But I don't want to have to nest everything unnecessarily inside `src/pages`, or have `src/pages` directories all over each feature.  I tried patching to amend the path replacement logic, but seems like it's deeper than that. Any advice you can share?

**Comment by Rettend** [comment]
+1
support for custom route paths would be great, `src/pages` seems hard coded for discovery and replacing the path strings, but a customizable option would be better. currently it's not configurable via regex.
