### ISSUE TITLE
Parentheses directories with a hyphen in the name 

### ISSUE THREAD

**Issue by Yoshintame** [oedotme/generouted#143]
### Describe the Bug

Parentheses directory with a hyphen in the name are interpreted as part of the route

### Generouted Version

1.17.0

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/github-1l15va

### Steps to Reproduce the Bug or Issue

1. Create parentheses directories with a hyphen in the name, for example: "(auth-test)"
2. Check the router file for generated routes, name of this directory will be part of the route

### Expected Behavior

Parentheses directory with a hyphen in the name should not be interpreted as part of the route

### Platform

- OS: macOS
- Browser: Chrome
- Browser version: 120

**Comment by oedotme** [comment]
@Yoshintame Thanks for reporting, this is now fixed at [v1.17.1](https://github.com/oedotme/generouted/releases/tag/v1.17.1)
