### ISSUE TITLE
Support for .mdx extension

### ISSUE THREAD

**Issue by dweiger** [oedotme/generouted#144]
Hey, 
would it be a conceivable feature to support .mdx extension in addition to .tsx/.jsx? 
I am currently using the plugin to create component documentation. I also use mdx for this documentation. 

I am currently using the following work around to get the path `/myPage` rendering mdx: 

Folder structure: 
```
pages
 myPage
  _myPage.mdx
   index.tsx
```
Inside index.tsx I simply export the mdx component: 
```jsx
import  MyPage from "./_myPage.mdx";

export default MyPage;
```

This works well with @mdx-js/rollup. Nevertheless, in my opinion it would be a great feature to support mdx - if used and set up in the project - as extension. So that the following would be possible: 

```
pages
 myPage.mdx
```

What do you think about it?

**Comment by oedotme** [comment]
Hey @dweiger, thanks for the suggestion. Could you please provide a StackBlitz repro with the example you've mentioned with `@mdx-js/rollup`?

**Comment by dweiger** [comment]
Hey, thanks for the quick reply. 
Here I have a [StackBlitz](https://stackblitz.com/edit/vitejs-vite-aqbwcp?file=src%2Fpages%2FmdxExample%2F_mdxExample.mdx) repo with the example.
