### ISSUE TITLE
Stackblitz link is broken

### ISSUE THREAD

**Issue by MyTotoro** [oedotme/generouted#146]
### Describe the Bug

stackblitz link is broken upon loading:

<img width="1203" alt="image" src="https://github.com/oedotme/generouted/assets/3621921/a451f323-168b-4269-a66f-3a3be687f617">

### Generouted Version

workspace:*

### Your Example Website or App or Reproduction

https://stackblitz.com/github/oedotme/generouted/tree/main/explorer?file=readme.md

### Steps to Reproduce the Bug or Issue

open the link

### Expected Behavior

show us newcomers the wonders of generouted

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]

**Comment by oedotme** [comment]
Hey @MyTotoro, thanks for submitting this issue.

It should be working now, the explorer is now using an actual version of `generouted` instead of the `workspace:*` protocol.
