### ISSUE TITLE
Generated routes output is sometimes not fully written to disk before being processed

### ISSUE THREAD

**Issue by timothympace** [oedotme/generouted#149]
### Describe the Bug

`generouted` uses the `buildStart` hook from `rollup` to [generate a routes file](https://github.com/oedotme/generouted/blob/main/packages/react-router/src/plugin/index.ts#L19-L21). Rollup's `buildStart` hook is compatible with `async` functions (`generate` in this case), but needs to return a promise in order for it to wait for any async work.

[Rollup build hook docs](https://rollupjs.org/plugin-development/#build-hooks)
[`buildStart` docs](https://rollupjs.org/plugin-development/#buildstart)

Fix provided in: https://github.com/oedotme/generouted/pull/148

### Generouted Version

1.18.2

### Your Example Website or App or Reproduction

Not a able to repro (race condition)

### Steps to Reproduce the Bug or Issue

Not a able to repro (race condition)

### Expected Behavior

Output file should be fully written to disk before moving on.

### Platform

- OS: N/A
- Browser: N/A
- Browser version: N/A

**Comment by oedotme** [comment]
Released at [v1.18.3](https://github.com/oedotme/generouted/releases/tag/v1.18.3)
