### ISSUE TITLE
Layout for pages at the top level?

### ISSUE THREAD

**Issue by user72356** [oedotme/generouted#15]
I missed something or this isn't documented. How can I create a layout for the top-level pages located right under the /src/pages/ folder? The example shows a posts.tsx layout file for files located under the posts/ directory, but what about pages that are located under the pages/ directory? I created a file called pages.tsx under /src but that didn't appear to work.

**Comment by bzbetty** [comment]
I believe a _app.tsx file in the pages directory does that currently?

**Comment by oedotme** [comment]
Yes exactly, `pages/_app.tsx` serves as pages root level layout, as of the Next.js routing conventions prior to their recent router update.
