### ISSUE TITLE
Folders without an index file create empty routes

### ISSUE THREAD

**Issue by ferretwithaberet** [oedotme/generouted#157]
### Describe the Bug

Folders without an index file create empty routes

### Generouted Version

1.18.5

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/vitejs-vite-jbnrwj?file=src%2Fpages%2Findex.tsx&terminal=dev

### Steps to Reproduce the Bug or Issue

1. Create a route structure like:
```
- segment1/
    - segment2/
        - index.tsx
- 404.tsx
```
2. Navigate to `/segment1`, observe that the router matches and an empty page is shown, even though there is no `index.tsx`

### Expected Behavior

When navigating to `/segment1`, it should show the 404 page.

### Platform

- OS: [e.g. macOS, Windows, Linux] Linux
- Browser: [e.g. Chrome, Safari, Firefox] Firefox Developer
- Browser version: [e.g. 91.1] 124.0b7 (64-bit)

**Comment by oedotme** [comment]
@ferretwithaberet That's mainly `react-router` matching for the routes config, you could see a related warning the devtools console — tbh that's kind of expected but feel free to report there if you find it an issue.

To get around that, you could try:
- Modifying the structure to `src/pages/segment1.segment2/index.tsx` to skip `segment1` matching
- You can switch back to `src/pages/segment1/segment2/index.tsx` if you need to add routes at `src/pages/segment1/`

Here's the updated example I've tested: https://stackblitz.com/edit/vitejs-vite-7e9xxf?file=src%2Fpages%2Fseg1.seg2.tsx

Hope that helps.
