### ISSUE TITLE
Loaders are executed twice when using React.StrictMode

### ISSUE THREAD

**Issue by ferretwithaberet** [oedotme/generouted#159]
### Describe the Bug

React router loaders run twice when using `React.StrictMode`

### Generouted Version

1.18.5

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/vitejs-vite-jbnrwj?file=src%2Fmain.tsx&terminal=dev

### Steps to Reproduce the Bug or Issue

1. Make a router with a route that has a `Loader`;
2. Add a `console.log` inside the `Loader`;
3. Add `React.StrictMode` above the `Routes` component;
4. Open browser console, navigate to the route and observe the `Loader` runs twice.

### Expected Behavior

The loader should only run once

### Platform

- OS: [e.g. macOS, Windows, Linux] Linux
- Browser: [e.g. Chrome, Safari, Firefox] Firefox Developer Edition
- Browser version: [e.g. 91.1] 125.0b5 (64-bit)

### Additional context

Might be related to https://github.com/remix-run/react-router/discussions/10605

**Comment by oedotme** [comment]
Hey @ferretwithaberet, thanks for opening this issue and providing the related issue. I just released [v1.18.7](https://github.com/oedotme/generouted/releases/tag/v1.18.7) with the fix.
