### ISSUE TITLE
Modals failing from 1.19

### ISSUE THREAD

**Issue by madsbuch** [oedotme/generouted#163]
### Describe the Bug

```
import { Modals } from '@generouted/react-router';
```

![Screenshot 2024-04-12 at 12 27 02](https://github.com/oedotme/generouted/assets/1612807/362db155-0d33-4374-b49c-6b1db45697e9)

I can't immediately see any migration notes for this in the README and the version bumb is also minor, so I would not expect any breaking changes.

### Generouted Version

1.19.*

### Your Example Website or App or Reproduction

sdcds

### Steps to Reproduce the Bug or Issue

Import as in the following:

```
import { Modals } from '@generouted/react-router';
```

### Expected Behavior

That it imports the component.

### Platform

- OS:  macOS
- Browser: Chrome

**Comment by oedotme** [comment]
@madsbuch Thanks for reporting this.

There was a note about that at the [v1.19.0](https://github.com/oedotme/generouted/releases/tag/v1.19.0) release notes. The `Modals` export is no longer available/need as it's included internally.

**Comment by madsbuch** [comment]
@oedotme 

First, thanks a lot for this library! (I really need to emphasis gratitude for this work, it makes my life much easier!)

Ahh, I see. That makes sense to put it there.

As a note: Me, like many others, reference the library using the ^-operator. We actually had ^1.16.1 in the package.json file. While i know it is good form to have tighter bounds on the versioning, I think most people agree that this is the way to keep up to date with new functions. As such, a breaking change like this would probably have been better to push to a major update, where people have to consider updating the package.

Anywho, I see that the release was cut yesterday, so we will probably see some people wake up to see some failing pipelines today :)

Again, thanks a lot!

**Comment by madsbuch** [comment]
A proposal to alleviate that would be to keep the export to `const Modal = () => null` and then remove the export from version 2 and forward.

**Comment by oedotme** [comment]
@madsbuch Thanks, very glad to hear that!

Thanks for the suggestion, I've included an empty `Modals` export with a deprecation warning at [v1.19.2](https://github.com/oedotme/generouted/releases/tag/v1.19.2)
