### ISSUE TITLE
vite preview not finding routes

### ISSUE THREAD

**Issue by waldo2810** [oedotme/generouted#165]
### Describe the Bug

Application throws the following error upon loading:

```
Unexpected Application Error!
404 Not Found
```

This not only happens when `npm run build` and then `npm run preview` in my computer. But also doing the same in a `Dockerfile`.

### Generouted Version

1.18.2

### Your Example Website or App or Reproduction

https://www.waasabi.co/

### Steps to Reproduce the Bug or Issue

1. Run `npm run dev`. Everything ok.
2. Run `npm run build` to build. Everything ok.
3. Run `npm run preview` to check prod version. Error.

### Expected Behavior

To load application just like in development mode.

### Screenshots or Videos

With `npm run dev`:
![image](https://github.com/oedotme/generouted/assets/65872529/d17e4c5f-57a7-4620-aefa-888c3f00f5be)

With `npm run build && npm run preview`:
![locally](https://github.com/oedotme/generouted/assets/65872529/b37f47cb-ac36-44f2-81c8-2a9764cfc447)

### Platform

- OS: Linux
- Browser: All of them.
- Browser version:

### Additional context

I know I am very likely missing something or doing something wrong, but I cannot find the answer anywhere, thanks for the support.

**Comment by oedotme** [comment]
@waldo2810 There's no enough information about your setup, it can be `Vite` or `generouted` related.

Could you please provide a minimal reproduction with [StackBlitz](https://stackblitz.com/)?

**Comment by waldo2810** [comment]
Seems like a Vite issue. This issue may be closed now.

**Comment by Here2Huynh** [comment]
@waldo2810 Hello, I seem to be having the similar issue but the 404 occurs when navigating to a page that is defined. Can you tell me what did you do to resolve that Vite issue?

**Comment by waldo2810** [comment]
> @waldo2810 Hello, I seem to be having the similar issue but the 404 occurs when navigating to a page that is defined. Can you tell me what did you do to resolve that Vite issue?

Hi, due to purely skill issues, I ended up using react-router directly.

One thing I can assure you, I wasn't able to reproduce in another environment so I'm positive it was an issue in my code.

I hope that helps and happy coding!
