### ISSUE TITLE
Can export const router ? how to set basepath?

### ISSUE THREAD

**Issue by 23233** [oedotme/generouted#168]
### Describe the Bug

routes.gen.tsx no export const router = createRouter({ routeTree: config });

but i want to set basepath , what can i do it?

```
            <RouterProvider router={router} basepath={"/admin"} />

```

### Generouted Version

"@generouted/tanstack-react-router": "^1.19.3",

### Your Example Website or App or Reproduction

no

### Steps to Reproduce the Bug or Issue

you konw

### Expected Behavior

export const Routes = () => <RouterProvider router={router} />

### Platform

window

**Comment by oedotme** [comment]
@23233 The `routes` tree/object is now exported at [v1.19.4](https://github.com/oedotme/generouted/releases/tag/v1.19.4)

You can now use it directly to customize the router:

```tsx
import { routes } from './routes.gen'

const router = createRouter({ routeTree: routes })
const Routes = () => <RouterProvider router={router} />
```
