### ISSUE TITLE
BUG: The regex that excludes layouts from routes also excludes any path that has a parent directory starting with `_`

### ISSUE THREAD

**Issue by vkefallinos** [oedotme/generouted#169]
https://github.com/oedotme/generouted/blob/5f6774d42925b7c5661199251432174419c7a368/packages/generouted/src/react-location.tsx#L10

For example the project `/home/vasi/projects/myproject/_ui/src/` or `/home/vasi/_projects/myproject/ui/src/` excludes any page other then _app or 404. When the `_ui` is renamed to `ui` the routes are correct.
Probably the solution is:
` ROUTES = import.meta.glob(["/src/pages/**/[\\w[-]*.{jsx,tsx,mdx}", "!**/src/pages/(_!(layout)*(/*)?|_app|404)*"]);`

**Comment by oedotme** [comment]
@vkefallinos Thanks for reporting!

This is now fixed at [v1.19.5](https://github.com/oedotme/generouted/releases/tag/v1.19.5)
