### ISSUE TITLE
Forwarding `ref` to Link component

### ISSUE THREAD

**Issue by yverby** [oedotme/generouted#172]
Using `Link` component (from `@generouted/react-router` package) as a dynamic component for other UI library components (e.g. `@mui/joy`) causes the following errors:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

This can be fixed locally in a project, but it does not seem convenient if you need to override it in every project.
Would it be possible to wrap `Link` component using `React.forwardRef` by default in the package?

Example: https://stackblitz.com/edit/github-wjvkrc-ibq3hw?file=src%2Fpages%2F_app.tsx

**Comment by oedotme** [comment]
@yverby Thanks for reporting.

I've included that change at the [v1.19.6](https://github.com/oedotme/generouted/releases/tag/v1.19.6) release.

Here's the example updated: https://stackblitz.com/edit/github-wjvkrc-qzmcqe?file=src%2Fpages%2F_app.tsx
