### ISSUE TITLE
Feature: I would like some routes to be lazy

### ISSUE THREAD

**Issue by notcod** [oedotme/generouted#173]
If you can implement or show me how to make some lazy routes.
I want /blog to be lazy, so I will name folder blog.lazy and all routes inside will be lazy (or whole route will be separate file if possible)
I made with custom integration for files that are .lazy to be lazy loaded, maybe you can implement it into core, here is gist https://gist.github.com/notcod/1ac86bdaa9b824a7f188b72064abd05b

**Comment by oedotme** [comment]
@notcod Thanks for the suggestion and sharing this integration!

I'd wait on adding this to core as there's already lazy and non-lazy integrations. Also having only one way to use lazy-loading would help to avoid any potential confusion.

Thanks again.
