### ISSUE TITLE
Pass options to the used router

### ISSUE THREAD

**Issue by ferretwithaberet** [oedotme/generouted#174]
Is there currently any way to pass options to the underlying used router?
I would like to use `@tanstack/react-router` and pass the `beforeLoad` option to it. I need this to provide data sequentially to the next matched route, for example auth data, and populate some `@tanstack/react-query` queries through `ensureQueryData`, but the queries depend on the results of the ones before them.

**Comment by oedotme** [comment]
@ferretwithaberet You can customize the router options by using the `routes` export:

```tsx
const router = createRouter({ routeTree: routes, ...options })
const Routes = () => <RouterProvider router={router} {...options} />
```

As for the route options, it supports the basic options similar to the other supported routers: `Loader` and `Action` functions, `Pending` and `Catch` components.

I had planned to update this integration to align more with TanStack but was awaiting first some TanStack APIs changes to make it possible. I'll update this issue once something new comes up.
