### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by erikdemarco** [oedotme/generouted#175]
### Describe the Bug

Currently when you use "npm run build" with this template:

https://github.com/oedotme/generouted/tree/main/examples/react-router

It will just export single entry from index.html. if we type in /posts/123 it will show 404

Please make a feature to support generating file path per route

### Generouted Version

1.19

### Your Example Website or App or Reproduction

 https://stackblitz.com/github.com/oedotme/generouted/tree/main/examples/react-router

### Steps to Reproduce the Bug or Issue

1. https://stackblitz.com/github.com/oedotme/generouted/tree/main/examples/react-router
2. npm run build

### Expected Behavior

generating file path per route

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Browser version: [e.g. 91.1]

**Comment by oedotme** [comment]
@erikdemarco SSG can be achieved through Vite + the used router. Generouted would be used only to provide (the already exported) routes to be used in a static router variant, while the HTML files can be generated by a script for instance.

I might take a look at that in the future and add it as one of the examples. For the time being, here's a related issue comment, in case you want to try it out: https://github.com/oedotme/generouted/issues/164#issuecomment-2074570218

**Comment by ydudyk** [comment]
Hi @oedotme!
I'm looking to achieve the same thing in my project and was wondering if adding it to the examples is still on the table. Would love to get some guidance on this
