### ISSUE TITLE
Allow '#' for <Link>

### ISSUE THREAD

**Issue by vuckookv3** [oedotme/generouted#179]
### Describe the Bug

Hello, I'm loving this package so far, good work!

I just have a minor suggestion.
What I like to do, while developing, and putting the links to pages I haven't created yet, is put '#' as href, just as a placeholder...

But currently, I am not allowed to do that, since it's not exported in type Path...

Could you maybe add that, or some other placeholder that we could use, so that <Link> doesn't have any action, but it's still there?

### Generouted Version

1.19.6

### Your Example Website or App or Reproduction

.

### Steps to Reproduce the Bug or Issue

.

### Expected Behavior

.

### Platform

.

**Comment by oedotme** [comment]
Hey @vuckookv3, thanks for your comment!

Personally I don't think that this placeholder pattern suggested would to be useful for others.

In your case, you still can use any placeholder value for the `to` or `href` property — but you'd get a TypeScript error. I'd suggest adding a `// @ts-expect-error` to suppress the error as it's temporary and you'll need to get back to it later:

```tsx
const Example = () => {
  return (
    <Link
      className=""
      // @ts-expect-error - placeholder link
      to=""
    >
      New Feature
    </Link>
  )
}
```

Hope that helps!
