### ISSUE TITLE
Duplicate router created when using custom router

### ISSUE THREAD

**Issue by ethanwu10** [oedotme/generouted#180]
### Describe the Bug

In the browser runtime, generouted unconditionally instantiates a browser router: https://github.com/oedotme/generouted/blob/3dde75f9af243b7c3bf256e5c5966bba3c7ef716/packages/generouted/src/react-router.tsx#L49

This causes event listeners (in particular for the history events) to be registered for this router, even if it is not ever used because the user is using the `routes` export directly to make their own router.

As a result, loader functions will be fired twice per browser history push/pop navigation (and probably in other instances as well). The router created by generouted is listening to events and responding by kicking off loader functions, even though it is never actually used.

### Generouted Version

1.19.6

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/sb1-cllb2d?file=src%2Fpages%2Findex.tsx

Note that this app is using the `routes` (lowercase) export from `@generouted/react-router` to build its own `BrowserRouter` to use, and is not using the `Routes` export.

### Steps to Reproduce the Bug or Issue

1. Navigate using a link
1. Navigate back using browser buttons
1. Observe that the loader count went up by 2 and that in the console, the loader fired twice in a row for the same navigation

### Expected Behavior

The loader should only have been executed once (by the router created by the user)

### Platform

- OS: macOS
- Browser: Chrome 129, Firefox 131

**Comment by oedotme** [comment]
@ethanwu10 Thanks for reporting this issue.

I just pushed a release [v1.19.7](https://github.com/oedotme/generouted/releases/tag/v1.19.7) to run `createBrowserRouter(...)` internally only when using the `<Routes />` export.

You can continue to use the `routes` export the same way to create a custom router with `createBrowserRouter`.

Thanks!
