### ISSUE TITLE
Duplicate router created when `Routes` is rerendered

### ISSUE THREAD

**Issue by ethanwu10** [oedotme/generouted#181]
### Describe the Bug

In the fix for #180, the browser router was changed to being created during each render of the `Routes` component:
https://github.com/oedotme/generouted/blob/567a35227a8fbb86c89ca6f395ae91fb6f9c95fa/packages/generouted/src/react-router.tsx#L49-L50

Thus, each time the `Routes` component was rendered, a completely new router is created and used.

This causes the same issues with e.g. loaders firing multiple times as seen in #180, but instead when using the `Routes` component (and not when creating your own `Router`).

### Generouted Version

1.19.7

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/sb1-1ln2g2?file=src%2Fpages%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Navigate using a link
1. Navigate back using browser buttons
1. Observe that the loader count went up by 2 and that in the console, the loader fired twice in a row for the same navigation

Note that since `StrictMode` is enabled, all render functions are called twice per render - thus 2 routers are created and we see loaders firing twice. If the component containing `<Routes />` rerenders for any other reason, more routers will be created.

### Expected Behavior

The loader should only have been executed once

### Platform

- OS: macOS
- Browser: Firefox 131

**Comment by oedotme** [comment]
Fixed in [v1.19.8](https://github.com/oedotme/generouted/releases/tag/v1.19.8) — Thanks for the follow up and for your contributions!
