### ISSUE TITLE
Allow the Catch function to pass the error along as an optional parameter

### ISSUE THREAD

**Issue by danfedericoadc** [oedotme/generouted#185]
### Describe the Bug

Feature Request: The Catch() function for each page works correctly as an error boundary, however the error is simply logged to the console, giving no insight as to what the error was on the screen or in the logs. 

`export function Catch() {
  return <Oops />;
}`

would be more useful if to do
`export function Catch(e) {
  return <Oops error={e.message} />;
}`

### Generouted Version

1.19.6

### Your Example Website or App or Reproduction

N/A

### Steps to Reproduce the Bug or Issue

1. Force an error to occur
2. Note the error is logged in the console
3. Note the error is caught by the Catch() error boundary
4. Note there is no way to access the error/stacktrace

### Expected Behavior

As a user, I expected to be able to access the error object within the Catch() block, but I am not able to

### Platform

- OS: macOS
- Browser: Chrome

**Comment by oedotme** [comment]
@danfedericoadc You can use the [`useRouteError`](https://api.reactrouter.com/v7/functions/react_router.useRouteError.html) hook from `react-router` to get access the error details.

FYI, the way you described is available at the Solid Router integration as its `ErrorBoundary` supports that.

Hope that helps!
