### ISSUE TITLE
Question: How to use dynamic query params?

### ISSUE THREAD

**Issue by arifluthfi16** [oedotme/generouted#186]
I have a question regarding  query params

Currently working with a feature that requires dynamic query params, something like:
```
navigate(`/dashboard/transaction/:transactionId${queryParams}`);
```

This understandably goes against generouted typesafe routing, but is there a work around for this? am i missing something?

**Comment by oedotme** [comment]
@arifluthfi16 If you're using the React Router integration, you could use the [object syntax](https://api.reactrouter.com/v7/interfaces/react_router.Path.html) for the path:
```tsx
navigate({ pathname: '/users/:id', search: '...', hash: '...' }, { params: { id: 'xyz' } })
```

Hope that helps!

**Comment by arifluthfi16** [comment]
Helps tremendously, thanks!
