### ISSUE TITLE
Authentication example

### ISSUE THREAD

**Issue by dewdad** [oedotme/generouted#2]
Thank you Omar! I love your work. Would it be possible to add an authentication example?

**Comment by oedotme** [comment]
Thank you for the kind words. I'm thinking now to make public/protected routes integrated in `generouted`, I'll first try a concept I have in mind and update this issue.

**Comment by oedotme** [comment]
After a second thought, I'm leaning toward an authentication approach with public/private routes that is applicable to frameworks like Next.js.

Here's the example I added to Render: https://github.com/oedotme/render#authentication-example that includes:
- Authentication context for the current user
- Routes guard to handle paths redirecting according to public/private paths declaration

This example was added after using `generouted` with Render. Would love to hear what you think about it.

**Comment by dewdad** [comment]
I did have a question for you, since I found your awesome template I've also come across https://github.com/hannoeru/vite-plugin-pages. Do you know of this plugin? It seems to provide a similar solution to generouted and has an active team behind it.
