### ISSUE TITLE
feat: react-router - add possibility to use HashRouter

### ISSUE THREAD

**Issue by Jisay** [oedotme/generouted#27]
First of all, thanks for your work! :-)

For now it's not possible to use the component with a [`HashRouter`](https://reactrouter.com/en/main/routers/create-hash-router) inseatd of a `BrowserRouter`. I know it's not recommended in the doc but for legacy reasons I need a hash in my urls.

Two ideas/proposals:
1. export the Array used to build the `BrowserRouter` (https://github.com/oedotme/generouted/blob/main/src/react-router.tsx#L32) and then use this Array in the app that use the component. Something like :
```js
// react-router.tsx
...
const routes = [
  { element: <App children={<Outlet />} />, children: [...regularRoutes, { path: '*', element: <NotFound /> }] },
]
const router = createBrowserRouter(routes)

export routes
export const Routes = () => {
  return <RouterProvider router={router} />
}

// my-app/index.tsx
import { HashRouter } from 'react-router-dom'
import { routes } from 'generouted/react-location'

const container = document.getElementById('app')!
createRoot(container).render(<HashRouter>{useRoutes(routes)}</HashRouter>)
```
2. being able to import `generouted/core` in our app and let the possibility to use the functions `generatePreservedRoutes` and `generateRegularRoutes` for building our "custom" routes. I think this can be useful if the root configuration in the `vite.config` is different. Such as :
```js
export default defineConfig({
  ...
  root: resolve(process.cwd(), 'client'),
  ...
});
```
In this case the glob patterns won't work and no pages will be found. Also page regex should also be configurable :-)

I don't know what's the best solution and what you think about the proposals or if you have other solutions :-)

**Comment by oedotme** [comment]
Thanks for sharing those ideas! It was already planned to export all routes array/object in some integrations, but it makes sense to export it in all integrations.

That will be useful in few ways, one of them is the use of different router types like memory, hash, etc.

Will try to make this update soon.

**Comment by oedotme** [comment]
Exporting the routes array is now available for all integration at the latest release ✨ https://github.com/oedotme/generouted/releases/tag/v1.6.1
