### ISSUE TITLE
Dynamic route at root level

### ISSUE THREAD

**Issue by Jisay** [oedotme/generouted#30]
Hello !

I'm wondering why it is not possible to create dynamic route at root level?

Considering this pages folder structure:
```
pages
├── 404.tsx
├── about.tsx
├── _app.tsx
├── index.tsx
├── [slug]
│   ├── index.tsx
│   └── foo.tsx
└── [slug].tsx
```

I want to be abble to access a route with given path: `/1234` or `/1234/foo`. But with the current implementation it's not possible.

I checked the core code and figure out that the code at https://github.com/oedotme/generouted/blob/main/src/core.ts#L43...L44 was responsible of the non creation of those routes paths. I have commented those lines and it looks like to work (tested with `react-router`).

Do you think it is possible to remove those lines safely?

**Comment by oedotme** [comment]
Hey, dynamic routes at the root level are disabled intentionally to not conflict with the preserved `pages/404.tsx` route.

If it was enabled, then if all the not matching routes will go through the `pages/[slug].tsx` and the `pages/404.tsx` will be always ignored.

To understand more, is there a specific case that you'll need `/:slug/something` instead of `/something/:slug`?

**Comment by Jisay** [comment]
Hey! Thanks for your answer. It's legit to not allow this.

In our case we are in a micro-frontend context with an iframe communication mechanism. Our top level application (which manage communication with the iframe) works as follow:
- it checks the first part of the path to know which application is running. For example `/foo/:slug/bar` will be detected as `foo` application.
- when this `foo` app is detected it will communicate to the iframe to load `/:slug/bar`.

This is the `foo` app that uses generouted and so doesn't care about `/foo`. Therefore we don't need a `foo` folder at root level but a `[slug]` instead.

At this point and discussing with my team, we will add a redirection in our `index.tsx` file if we detect a well formatted `slug` param. We will create a `/something/:slug` route and as we will receive something like `/myAwesomeSlug/bar` in our iframe we will check the format of the first part (myAwesomeSlug) and redirect to `something/myAwesomeSlug/bar`.

**Comment by oedotme** [comment]
Thanks for the explanation! That sounds good!
