### ISSUE TITLE
React Location vs. Tanstack React Router?

### ISSUE THREAD

**Issue by swernerx** [oedotme/generouted#31]
Hi! Just wanted to drop how happy I am that someone has solved this! Magical indeed. Thanks!

That said... I was wondering whether React Location is kind of the old version on Tanstack Router. The first one is 8 months old while second one in in current development as it seems. Do you see how to migrate this solution to the "new router"?

**Comment by oedotme** [comment]
@swernerx Thanks for mentioning that!

Sure, I'm very excited about adding Tanstack's new Router, I'm planning to add it whenever I have the time. #34

I was also thinking to add type-safety at least for link paths to other integrations as well through code generation, and that will mostly come after adding Tanstack Router.

**Comment by oedotme** [comment]
Support for React Router as a plugin to provide some type-safety landed at https://github.com/oedotme/generouted/releases/tag/v1.7.0
