### ISSUE TITLE
Error boundary's not working in React Router because default errorElement resolves to null instead of component

### ISSUE THREAD

**Issue by hi019** [oedotme/generouted#35]
If an error is thrown in a file which doesn't export an `ErrorElement`, the default React Router error boundary will be displayed with this error: `Uncaught Error: Element type is invalid. Received a promise that resolves to: null. Lazy element type must resolve to a class or function.` This happens even if an error boundary is used. If the file does export `ErrorElement`, then the element will be rendered with the `Uncaught Error: ...` mentioned above as the error.

#### Why
In https://github.com/oedotme/generouted/blob/main/packages/generouted/src/react-router.tsx#L17, if no `errorElement` is found for the route, we use a lazy component which resolves to `null`.

```ts
const ErrorElement = lazy(() => module().then((module) => ({ default: module.ErrorElement || null })))
```

When an error is thrown in the component, React Router tries to render the corresponding lazy `ErrorElement`. If no `ErrorElement` is exported from the module, it will try to use the `null` one, but React will throw an error because lazy component's must resolve to a class or function.

#### Fix
I think this problem is the same as the one from https://github.com/oedotme/generouted/pull/32. The same solution there works, but I would throw only the error instead of adding text to it:

```ts
export function DefaultErrorElement() {
  throw ${useRouteError()}
}
```

That way, the other error boundaries we bubble up to will get the original error.

**Comment by oedotme** [comment]
Hey, thanks for detailing the issue. I just applied the fix to expose the default React Router error as at #32 and you suggested.

https://github.com/oedotme/generouted/releases/tag/v1.6.12

**Comment by hi019** [comment]
Great, thank you for this project!
