### ISSUE TITLE
New convention for layout groups, optional routes layouts?

### ISSUE THREAD

**Issue by oedotme** [oedotme/generouted#36]
There are two SvelteKit conventions that might be useful in some cases that I'm thinking to add:

#### Pathless layout groups https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

- By wrapping a directory name with `()`: `src/pages/(app)/...`
- Related #19

##### Example

```shell
src/pages/
├── (app)/
│   ├── _layout.tsx
│   ├── dashboard.tsx      →  /dashboard      wrapped by (app)/_layout.tsx
│   └── item.tsx           →  /item           wrapped by (app)/_layout.tsx
├── (marketing)/
│   ├── _layout.tsx
│   ├── about.tsx          →  /about          wrapped by (marketing)/_layout.tsx
│   └── testimonials.tsx   →  /testimonials   wrapped by (marketing)/_layout.tsx
└── admin/
    ├── _layout.tsx
    └── index.tsx          →  /admin          wrapped by admin/_layout.tsx
```

#### Optional route segment https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

- Support for React Router [v6.5.0+](https://github.com/remix-run/react-router/releases/tag/react-router@6.5.0)
- By wrapping the dynamic route with extra `[]`: `src/pages/[param]/about.tsx`  →  `src/pages/[[param]]/about.tsx`

##### Example
- `src/pages/[[lang]]/about.tsx`  →  `/:lang?/about`
- `/:lang?/about` will match both `/:lang/about`  →  `/en/about` and `/about`

**Comment by monarcode** [comment]
Perfect, this would solve a lot of problems

**Comment by oedotme** [comment]
Support for both is now added at [v1.6.14](https://github.com/oedotme/generouted/releases/tag/v1.6.14)
