### ISSUE TITLE
Question: fallback loading element for routes

### ISSUE THREAD

**Issue by monarcode** [oedotme/generouted#39]
How do i show a loading state when a route is being fetched?

eg, in nextjs 13, i can create a loading.tsx file and return some jsx, which will server as a suspense fallback element when child routes are being fetched.

Is there a built in way to achieve same with this package?

**Comment by oedotme** [comment]
Pending state depends on the routers/integrations support for it. Right now only two integrations support it:
- **React Location**: by exporting route-based `PendingElement` component
- **New TanStack React Router**: by exporting route-based `Pending` component
