### ISSUE TITLE
How to configure route based code splitting?

### ISSUE THREAD

**Issue by amazzat** [oedotme/generouted#4]
Hi there, found your blog and this package from it. Really like idea of file based routing in vite for working on classic spa apps. 
I want to try how to configure code splitting for routes. Is this possible, because [description](https://github.com/oedotme/generouted#route-based-code-splitting-and-pre-loading) does not mention anything?

**Comment by oedotme** [comment]
Hey, I'm glad to hear that!

There's no customization option for code splitting at the moment, each route is split into its own file at build time, except for the `_app.tsx` and `404.tsx` which are included in the main bundle.

It made sense to have code splitting enabled by default for smaller main bundle specially when you start having a lot of pages. Slower routes transition was the main issue I found, but that became much better after using `react-location` with pre-loading.

Could you tell me what you need to configure in the code splitting setup?

**Comment by amazzat** [comment]
Sorry, it just wasn't clear for me that code splitting was enabled by default, thank you for response!
