### ISSUE TITLE
If segment contains a hyphen, it becomes an optional route.

### ISSUE THREAD

**Issue by megatkhs** [oedotme/generouted#40]
If you create a file with a name like `pages/foo-bar.tsx`, it will be recognized as `/foobar?`.
Is this the intended behavior?

```
./src/pages
├── foo-bar.tsx
└── index.tsx
```

**Comment by oedotme** [comment]
Hey, thanks for reporting. This was indeed an issue with the optional pattern and has been fixed at the latest release https://github.com/oedotme/generouted/releases/tag/v1.7.3

Even though this wasn't an optional segment but its pattern caused an issue with any segment containing a dash `-`, now `pages/foo-bar.tsx` should have `/foo-bar` as a route.
