### ISSUE TITLE
Tried the tanstack router plugin with latest version of tanstack react router and its giving errors.

### ISSUE THREAD

**Issue by spa5k** [oedotme/generouted#41]
Mainly, in the route.gen.tsx file, its unable to find 2 imports - 

```ts
import { createReactRouter, createRouteConfig, lazy, RouterProvider } from '@tanstack/react-router'
```
`createReactRouter, createRouteConfig`.

If we move back @tanstack/react-router version to what is used in example, it does work.

**Comment by oedotme** [comment]
Hey, thanks for opening this. Yes `@tanstack/react-router` had some API changes recently and it will be updated in the generouted plugin soon.

**Comment by spa5k** [comment]
Bro, you are a champ, fixing it so quickly. 🎉

**Comment by oedotme** [comment]
Thanks man! Please let me know if all works as expected!
