### ISSUE TITLE
Cannot find module '@generouted/react-router/client' or its corresponding type declarations.

### ISSUE THREAD

**Issue by manV** [oedotme/generouted#42]
I am trying `@generouted/react-router` following steps mentioned in the plugin's readme.

The generated `routes.gen.tsx` contains an import
```js
import { components, hooks } from '@generouted/react-router/client'
```

Looking into plugin's package.json I found these module exports
```json
"exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "require": "./dist/index.cjs",
      "import": "./dist/index.js"
    },
    "./client": {
      "types": "./src/client/index.ts",
      "import": "./src/client/index.ts"
    }
  },
```

but there is no src directory in the installed plugin module

![image](https://user-images.githubusercontent.com/4988376/216141110-8a651e8d-18f3-40da-ba21-21b2bbafebda.png)

Apologies if I have missed something.

**Comment by oedotme** [comment]
Hey @manV, thanks for reporting this.

I realized that I forgot to add `src/client` to `package.json`'s `files`, only `dist` was declared so it was the only available directory.

`src/client` is also now added and should exist in the published package.

**Comment by oedotme** [comment]
The fix is in this release https://github.com/oedotme/generouted/releases/tag/v1.7.3
