### ISSUE TITLE
[Feature Request] Add config to custom route style: next, remix, nuxt, etc.

### ISSUE THREAD

**Issue by saintwinkle** [oedotme/generouted#48]
Hello, Can we have a route style config if possible, like https://github.com/hannoeru/vite-plugin-pages#routestyle.

Maybe we should add configuration system first? Something like:

```jsx
<Routes
  config={{
    routeStyle,
    loaderName,
    actionName,
    errorElementName,
    ...
  }}
/>
```

**Comment by oedotme** [comment]
Hey @saintwinkle,

As `generouted` is inspired by many frameworks like Next.js, Remix, Expo, Docusaurus and SvelteKit, the features/conventions would be limited to the chosen route style (which is not ideal IMHO).

If we want to combine `generouted` features/conventions with each route style, it might conflict and/or it would be super confusing to the users.

On the other hand, managing one convention and support multiple routers (for React and Solid as of now) is the goal of `generouted`, but with multiple routing styles and multiple routers I think it would get complicated.

Please let me know if this addresses what you're thinking about.

**Comment by saintwinkle** [comment]
@oedotme 

Thanks for your detailed reply, I've got the main goal of `generouted`.
