### ISSUE TITLE
Changing the name of the generated file

### ISSUE THREAD

**Issue by gino** [oedotme/generouted#49]
Hi there,

I am wondering if it's possible to change the name of the routes file that gets generated. I would prefer something like `_routes.tsx` instead of `routes.gen.tsx`, if possible.

Thanks a lot.

**Comment by oedotme** [comment]
Hey @gino, It was planned to support two config options for the plugins. The first is the same as what you mentioned to provide a custom generated file name and the other for disabling formatting with `prettier`.

Right now the plugins use the defaults, but should be straight forward to support user options.

I'll update this issue once added. Thanks!

**Comment by oedotme** [comment]
It's now possible to provide options to `generouted`'s Vite plugins, here's the usage with the default values:

```ts
// vite.config.ts

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import generouted from '@generouted/react-router'

export default defineConfig({
  plugins: [react(), generouted({ output: 'routes.gen.tsx', format: true )],
})
```

Added at https://github.com/oedotme/generouted/releases/tag/v1.7.14
