### ISSUE TITLE
Negative look behind in react-router causing app not to load on mobile

### ISSUE THREAD

**Issue by anth0ni3** [oedotme/generouted#50]
`  const index = /(?<!pages\/)index\.(jsx|tsx)$/.test(key) ? { index: true } : {}`

in "packages > generouted > src > react-router.tsx > generateRegularRoutes(). Line 22", the index variable contains regex that cause app to fail in mobile browsers.

**Comment by anth0ni3** [comment]
I'm guessing this is because negative look behind in regex is not supported in most browsers.

**Comment by oedotme** [comment]
Hey @anth0ni3, thanks for reporting this!

Yes, it should be updated. Also there's no specific need to use negative look behinds here.

I'll close this issue once updated.

**Comment by oedotme** [comment]
It's now updated at https://github.com/oedotme/generouted/releases/tag/v1.7.14
