### ISSUE TITLE
[Discussion] - Support Sentry wrapCreateBrowserRouter or possibly make the router variable a function

### ISSUE THREAD

**Issue by ErlendS** [oedotme/generouted#53]
Hey me and my team really enjoy this plugin! Amazing work you have done here!

We are having a bit of an issue implementing Sentry we wondered if you could take a look at:

###  The problem
We are trying to implement Sentry performance tracing in our vite app. To do this we need to wrap a sentry function 'wrapCreateBrowserRouter' around 'createBrowserRouter'. [Docs here](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/#react-router-v6)

#### Our current fix:
We tried circumventing this issue by importing the generated `routes` variable and then making our own Routes component. This works, but this causes double fetching on the initial load since createBrowserRouter is still called in "routes.gen.tsx".

### Possible solution 1 - Make router a function
We think the easiest solution could be making the router a function: 
``` ts
const router = () => createBrowserRouter([{ element: <App />, children: routes }])
// ...
// then update Routes to call it
export const Routes = () => <RouterProvider router={router()} />

```
This way `createBrowserRouter` is not called unless we use the Routes component.

### Possible solution 2 (trickier) - Support function propagating
Alternatively if genroutes supported passing an optional function to wrap "createBrowserRouter" that would be great, but sounds like a lot more  work for an issue not many people seem to have.

eg:
```ts
// vite.config.ts
 plugins: [
      genroutes({browserWrapper: wrapCreateBrowserRouter}),
      ...
```

----------------------

We understand that this is a pretty specific problem for us so no worries if this is out of scope for request you are taking in atm. Please let me know if there is anymore info you need, and thanks again for this great plugin.

**Comment by oedotme** [comment]
Hey @ErlendS, I'm glad to hear that and thanks for providing all the details!

I realized that the `<App />` is missing from the exported `routes` so it's now added. Also `createBrowserRouter` can be used directly in the `Routes` component as there's no need to define the `router`:

```tsx
export const routes = [{ element: <App />, children: [...config, { path: '*', element: <NoMatch /> }] }]
export const Routes = () => <RouterProvider router={createBrowserRouter(routes)} />
```

Using the `routes` should work now as expected, you can test it out in the latest release [v1.7.17](https://github.com/oedotme/generouted/releases/tag/v1.7.17).

Please let me know if you still have issues with the integration.

**Comment by ErlendS** [comment]
This is exactly what we needed. Thank you so much!  Really appreciate the quick response!
