### ISSUE TITLE
Vite plugin does not work in a monorepo context

### ISSUE THREAD

**Issue by obedm503** [oedotme/generouted#54]
Tried using the react-router vite plugin in a monorepo. The plugin does not use relative paths so it generates `routes.gen.tsx` in `/src/routes.gen.tsx` instead of `/packages/[app]/src/routes.gen.tsx` even when `vite.config.ts` lives in `/packages/[app]/vite.config.ts`. Happy to provide an example reproducing the issue.

**Comment by oedotme** [comment]
Hey @obedm503, I was expecting the relative paths to work as expected in a monorepo context. The examples in the `generouted` repo are monorepo packages and it works correctly.

Yeah, it would be very helpful if you could provide an example to reproduce this issue.

**Comment by oedotme** [comment]
I've tested this in another monorepo and it worked as expected.

I'll close this issue but please feel free to reopen with a repro if you still having this problem.
