### ISSUE TITLE
Type safe redirect 

### ISSUE THREAD

**Issue by t-animal** [oedotme/generouted#55]
The vite plugin is awesome, but when redirecting using `import { redirect } from "react-router-dom";` the type-safety from `routes.gen.tsx` gets lost. It would be cool if it also exported a `redirect` function that knew about the available paths.

**Comment by oedotme** [comment]
Thanks for the suggestion! `redirect` utility is added in [v1.7.18](https://github.com/oedotme/generouted/releases/tag/v1.7.18).

It's now exported as well from `routes.gen.tsx` with the other type-safe exports.
