### ISSUE TITLE
plugin is not compatible with Vite's hot reload

### ISSUE THREAD

**Issue by binghuis** [oedotme/generouted#57]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/20395726/221372446-18e2c5c8-0eeb-4c2f-ae41-78c67a7c6eb0.png">

**Comment by oedotme** [comment]
Do you see the same output when editing a page file?

**Comment by binghuis** [comment]
Yes, when you continuously modify a page element, the problem of hot update failure will occur. I'm considering whether to implement hot update for routes.gen.tsx when the page is updated.
When I disabled hot updates for routes.gen.tsx in the Vite configuration, the modifications to the page no longer triggered hot updates, but the file content was still updated normally.
I'm not sure if this operation will have any unknown effects on other operations.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/20395726/221463877-29c23cff-881d-4f77-b981-93edc37740b4.png">

**Comment by binghuis** [comment]
I know why modifying page code causes page reload of route.gen.tsx. The following code will cause a reordering, leading to changes in route.gen.tsx file.
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/20395726/221775821-f89aa579-c9f0-4f48-9e73-a9a68027cb7a.png">

**Comment by binghuis** [comment]
fix: [PR](https://github.com/oedotme/generouted/pull/59)
