### ISSUE TITLE
Warning: Can't perform a React state update on a component that hasn't mounted yet.

### ISSUE THREAD

**Issue by gino** [oedotme/generouted#62]
Hi there!

First of all, I am not quite sure if this is an issue with `generouted` or `@tanstack/react-router`, or even with Relay (the GraphQL client I use for data fetching) but I noticed that my page gives me the following error after a few refreshes:

`Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component.`

I realised that the error disappears if I get rid of the `lazy()` import from the generated routes file and manually import the component in there.

Could this be an issue with TanStack router or perhaps with the way of how I fetch data in combination with React 18 / Suspense? I am not quite sure what's happening. Maybe any of you are able to help me out.

Thanks a lot, I appreciate it!

**Comment by oedotme** [comment]
Hey @gino, thanks for reporting this.

I believe it's not related to `generouted`, and I was thinking about having routes lazy-loading/splitting optional.

If you still have this issue, could you please provide a StackBlitz repro?

Thanks!

**Comment by gino** [comment]
Hey @oedotme, I realised that this is indeed an issue with lazy loading my routes. I am not quite sure why this would occur any issues but whenever I disable lazy loading, my component does not throw this error.

Not quite sure what's going on but I'll try to figure it out!
