### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by willowloveforever** [oedotme/generouted#63]
Hello. In the latest version 1.7.20 of generouted, using the<Link>tag of ant design, the route can be updated after clicking, but the page is not updated. Hope it can be solved.thanks

**Comment by willowloveforever** [comment]
<Link>tag

**Comment by willowloveforever** [comment]
Link tag

**Comment by oedotme** [comment]
Hey, was it working with you in `v1.7.19`?

In any case, could you please provide a repro using something like StackBlitz or CodeSandBox?
