### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by binghuis** [oedotme/generouted#65]
routes.gen.tsx
```
import app from "./pages/_app";
const App = app || Outlet;
```
_app.tsx
```
import { Link, routes } from "@/routes.gen";
```
Two files referencing each other will result in circular dependency issue, and require modification to the file structure.

**Comment by binghuis** [comment]
it is possible to generate a separate file for static components.

**Comment by binghuis** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/20395726/222875964-b1b139de-4bee-4af0-8975-1269ca70e74f.png">

**Comment by oedotme** [comment]
The problem here is only in `routes`. I also believe if `rotues` is in another file, it would still throw this error.

Because `routes` is using `app` directly and you're trying to reference it back in `app`:



```tsx
// src/routes.gen.tsx

import app from "./pages/_app";
const App = app || Outlet;

// ...

export const routes = [{ element: <App />, children: [...config, { path: '*', element: <NoMatch /> }] }]
```

```tsx
// src/pages/_app.tsx

import { Link, routes } from "@/routes.gen"
```

<br>

This error is expected, as at the moment `routes` is intended to be used only for custom `Router` in the application entry.

**Comment by binghuis** [comment]
In general, the _app file will not directly reference Routes and routes. However, since the layout is set in the _app file, it will reference components like Link and Navigate from the routes.gen.tsx file. Therefore, if constants like Link and Navigate are placed in a separate file, it is possible to avoid circular dependency issues.

**Comment by binghuis** [comment]
"Indeed, routes should not be imported in _app file, it was my mistake to put it in. However, circular dependency caused by Link can indeed be resolved by separating the file. What do you think?"

**Comment by oedotme** [comment]
Yeah that's definitely something to look into. Thanks again for the suggestion.

Although I think it might be fine at the moment, I was exploring restructuring possibilities to improve on the point you mentioned and also to play well with some upcoming features.
