### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Unintendedz** [oedotme/generouted#68]
https://github.com/oedotme/generouted/blob/eb2604c57ebc16f31b08b8980763c2ca9694f091/plugins/react-router/src/template.ts#L10

`rediect` -> `redirect` ?

**Comment by oedotme** [comment]
Yeah indeed, thanks for reporting this.

**Comment by oedotme** [comment]
Fixed in [v1.11.1](https://github.com/oedotme/generouted/releases/tag/v1.11.1)
