### ISSUE TITLE
Routes not found when running vite plugin from Nx monorepo

### ISSUE THREAD

**Issue by mcreenan** [oedotme/generouted#73]
I have setup a mono-repo with Nx and Vite as the bundler.  I tried following the guide at https://github.com/oedotme/generouted/tree/main/plugins/tanstack-react-router and also https://github.com/oedotme/generouted/tree/main/examples/react-router/basic, but in both cases it doesn't work:

```
➜  workspace git:(master) ✗ npx nx serve demo

> nx run demo:serve:development

5:51:34 PM [generouted] 0 routes in 69 ms
node:fs:594
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './src/routes.gen.tsx'
    at Object.openSync (node:fs:594:3)
    at writeFileSync (node:fs:2207:35)
    at T (/project/home/mcreenan/workspace/node_modules/@generouted/tanstack-react-router/dist/index.cjs:48:211) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './src/routes.gen.tsx'
}

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project demo failed

   Failed tasks:
   
   - demo:serve:development
   
   Hint: run the command with --verbose for more details.
```

Here's a codesandbox showing the issue -- https://codesandbox.io/p/sandbox/admiring-wescoff-hzfm0g?file=%2FREADME.md

**Comment by mcreenan** [comment]
I tried some troubleshooting.  If I modify the call to fastglob to be `./apps/demo/src/pages/...` instead of just `./src/pages/...` then it finds the page file(s).

**Comment by oedotme** [comment]
The repro doesn't seem to work for some reason.

Could you try logging `console.log({ cwd: process.cwd() })` from both the monorepo root and when changing directory to `apps/demo`?

I tried now from a monorepo and both output the same path. If you have different paths, which I suspect, maybe try setting the `vite.config.ts` `root` option to the correct root path.

Please let me know if that works for you.

**Comment by mcreenan** [comment]
The cwd is the root of the monorepo when logging it from the project's `vite.config.ts` in `apps/demo/`.

The same is true when logging the cwd from https://github.com/oedotme/generouted/blob/main/plugins/tanstack-react-router/src/generate.ts#L15

Setting the `root` option in `vite.config.ts` has no erffect on that, which makes sense because it's the invocation of the `generouted()` plugin function which is what does the scan, and that's being called before the vite config is actually set.

**Comment by oedotme** [comment]
I've tried running `generouted` PNPM Workspaces with or without Turborepo and it works in both cases. I still believe the main issue here with Nx is the single `package.json` in the monorepo root, which messes the sub-packages working directory for some tools.

Could you try [`generouted`'s latest React Router integration](https://github.com/oedotme/generouted/tree/main/plugins/react-router) with this Nx recipe? https://github.com/nrwl/nx-recipes/tree/main/pnpm-workspace It uses different structure and potentially should work with the current setup.

**Comment by obedm503** [comment]
This is the same issue I brought up in #54. `writeFileSync` creates the file relative to the `cwd` instead of relative to where it is called. It makes sense that it would try to create the file in `/src/router.ts` instead of `/apps/[app]/src/router.ts`.

A simple solution might be to allow the `output` option to be a full path instead of just a file name relative to "[`./src/`](https://github.com/oedotme/generouted/blob/7419745fd16b6fd8594f46eef78ea7b739fb35b0/plugins/react-router/src/plugin/generate.ts#L72)".

**Comment by oedotme** [comment]
Hey everyone, to just to confirm - currently `generouted` is tested to work with workspaces aware monorepo tools (tested with `pnpm` or `turborepo` + `pnpm`). I'll try to look into `nx` support soon and have a section about monorepos in the docs.

Thanks for the suggestion @obedm503, the thing is the resolving happens on a plugin and runtime levelts; setting the `output` option wouldn't work for both. I'm thinking about a change in the patterns that could resolve this.

**Comment by mnlbox** [comment]
@oedotme I have the exactly same issue and error message with NX and generouted. Can you explain clearly how can I fix this by using "custom integeration"?

**Comment by mnlbox** [comment]
@oedotme I followed same steps as mentioned here. Now the pages are created but I'm getting only a blank white page in the output when I feth any of the pages. Any idea?

**Comment by oedotme** [comment]
@mnlbox That mostly indicates that the [routes `glob` pattern](https://github.com/oedotme/generouted/blob/main/examples/react-router-custom-path/client/src/routes.tsx#L12) might have an issue.

Could you please provide a StackBlitz example with an up-to-date NX project with `generouted`?
