### ISSUE TITLE
Elegant exclude certain files in the pages directory

### ISSUE THREAD

**Issue by aladdin-add** [oedotme/generouted#74]
we are developing a large react app, and we put a few non-page files in the folder.

```bash
├── src
|  ├── entry
|  ├── common
|  |  ├── components
|  |  ├── constants
|  |  ├── env
|  |  ├── hooks
|  |  ├── store.ts
|  |  ├── types
|  |  └── utils
|  └── pages
|     ├── choose-role
|     |  ├── api.ts
|     |  ├── components
|     |  ├── constants.ts
|     |  ├── utils.ts
|     |  └── index.tsx // the page file

```

the other files than `index.tsx` are not routes (e.g. `/choose-role/utils` 
). So, we want to exclude these files when auto-generating the routes.

I can imagine three ways:

1. adding a `_` before all these filenames. e.g. `utils.ts` => `_utils.ts`. awful tho. 😅
2. adding an excluded files list. (Thankfully, we have a good name convention for these files).
3. renaming the `index.tsx` => `page.tsx`(similar to the `app` dir, other files should be excluded by default.)

my personal preference is 3 ≈ 2 > 1. 

is `generouted` adaptable for our case? would like to see your insights! ❤️

**Comment by oedotme** [comment]
Hey @aladdin-add, I see in your case many files at `src/pages` are `.ts` and actually those are ignored by default, as `generouted` looks only for pages with `.tsx|.jsx` extensions.

Currently in `generouted`, the ignore patterns for `.tsx|.jsx` pages are [inspired by Docsuraus](https://docusaurus.io/docs/creating-pages). You can ignore page(s) either by prefixing each page with `_` or by prefixing a parent directory with `_`. So that should work as of now:

```shell
├── src
|  ├── entry
|  ├── common
|  |  ├── components
|  |  ├── constants
|  |  ├── env
|  |  ├── hooks
|  |  ├── store.ts
|  |  ├── types
|  |  └── utils
|  └── pages
|     ├── choose-role
|     |  ├── _components      
|     |  |   ├── button.tsx   # ignored by parent _ prefix
|     |  |   └── card.tsx     # ignored by parent _ prefix
|     |  ├── _modal.tsx       # ignored _ prefix
|     |  ├── api.ts           # ignored .ts by default
|     |  ├── constants.ts     # ignored .ts by default
|     |  ├── utils.ts         # ignored .ts by default
|     |  └── index.tsx        # matches
```

Seems to be option `2` if I understand correctly.

<br>

Also I found out that the ignored paths were included in the generated types, but it was fixed few minutes ago. You can upgrade to [v1.11.3](https://github.com/oedotme/generouted/releases/tag/v1.11.3) and try it out.

Lastly here's a related issue #9 for co-locating non-pages in `src/pages`.

Hope that helps!

**Comment by aladdin-add** [comment]
Thanks for the quick reply! I mean option 2 is to opt-in something like:

```js
export default defineConfig({
  plugins: [
    react(),
    generouted({excludedFiles: ["components/**/*"]})
  ]
});
```

so that `components` does not have to be prefixed("_components").  wdyt?

**Comment by aladdin-add** [comment]
sure,I just like having an option; as how the option is designed, I'm totally open.

**Comment by oedotme** [comment]
I've updated the plugins now to accept a `source` option in [v1.11.4](https://github.com/oedotme/generouted/releases/tag/v1.11.4). I went with this option as it can be used for extending ignore patterns while having other potential use cases as well.

`source` can be `string | string[]`, in your case it would make sense to use an array with the default pattern at the beginning of the array, then to include the ignore pattern(s) after in the array. I've tested with the following config:

```tsx
export default defineConfig({
  plugins: [
    react(),
    generouted({ source: ['./src/pages/**/[\\w[-]*.{jsx,tsx}', '!./src/pages/**/components/**'] })
  ],
})
```

The second pattern start with `!` to be ignored. You can check [`fast-glob`](https://github.com/mrmlnc/fast-glob) docs for patterns reference.

<br>

For the `<Routes>` component to follow the same ignore pattern, you'll need to have a custom file, based on the current integrations at `packages/generouted/src/*` using `generouted` core. Should be something similar to #28

**Comment by aladdin-add** [comment]
Big thanks! I'll give it a try.
