### ISSUE TITLE
MakeGenerics

### ISSUE THREAD

**Issue by tomatoword** [oedotme/generouted#75]
Hello, can I define only one MakeGenerics in a single file? Because I need to send two axios requests and store the returned data before the first rendering of the functional component. What should I do? thanks

**Comment by oedotme** [comment]
Hey @tomatoword, it seems you're using the `react-location` integration. Indeed, the `MakeGenerics` type should be declared only once, as there's only one `Loader` per route/file.

If you need to make multiple requests, you can totally do that then return an object for example from the `Loader`:

```tsx
type First = { id: string }
type Second = { name: string }

type Route = MakeGenerics<{ LoaderData: { first: First; second: Second }}>

export const Loader: LoaderFn<Route> = async ({ params }) => {
  const first = await axios.get('/first')
  const second = await axios.get('/second')
  return { first, second }
}

export default Component() {
  const { data } = useMatch<Route>()
  // data.first, data.second
  
  return ...
}
```

Hope that helps!

**Comment by tomatoword** [comment]
Thank you very much. It's very useful. Then, can I ask another question? It seems that after generouted 1.6.9, the file [slug].tsx does not support the transfer of parameters. The problem is that the route will jump, but the updated parameters are not passed to [slug].tsx. This causes the route to change, but the page does not refresh. For example, the recently updated version 1.11.1 has this problem. thank you.
