### ISSUE TITLE
How to get `Path` in automatically generated `router.ts`?

### ISSUE THREAD

**Issue by Unintendedz** [oedotme/generouted#79]
First off, I wanted to say thank you for developing this project! It's been a huge help to me.

I do have a question, though. I want to use the `Path` type from the `router.ts` file for autocomplete suggestions in some parts of my project. However, since that file is generated automatically and `Path` is not exported, I don't know how to do this. Do you have any suggestions on how I can achieve this?

I'm sorry if I'm missing something obvious, or if this question is too basic. Any advice you can give would be much appreciated!

**Comment by oedotme** [comment]
Hey @Unintendedz, thanks for sharing!

No worries, that totally makes sense. The generated types are now exported by default in [v1.11.5](https://github.com/oedotme/generouted/releases/tag/v1.11.5).
