### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by Briscoooe** [oedotme/generouted#87]
Absolutely love the idea and implementation. Suits my needs perfectly and works out of the box really nicely. 

I notice the activity has dropped off a bit so wondering if the project will be maintained going forward? I'd be using it on a pretty mission critical project and I'm scoping out the viability of various solutions. 

Thanks!

**Comment by oedotme** [comment]
Hey @Briscoooe, thanks a lot for sharing that!

I'm using this project in personal and work projects and have no plans to abandon it. Overall I'm pretty happy with it and it works very well for my use cases. The main areas I'm planning to improve/work on in the near future are:
- Improving docs and examples
- Adding tests and improving certain abstractions
- More type-safety

<br>

Worth mentioning also that there's a small project I added recently to `generouted` to help understanding and visualizing file-based routing, `generouted/explorer` which provides an interactive files tree based on the `src/pages` files (running in dev mode) - mainly to inspect/explore the routes layouts used and how the route path resolves for each route. 

You can try it online via StackBlitz https://stackblitz.com/github.com/oedotme/generouted/tree/main/explorer

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20151138/235285663-cf0d929f-daf5-4414-b338-bae01ecfbd9c.png">

Thanks for sharing your concern and please let me know if you have any questions.

If you guys have more ideas for new features or areas to improve, please let me know!

**Comment by Briscoooe** [comment]
Amazing, thank you! Happy to contribute to the development of this if we choose to use it.
