### ISSUE TITLE
Code splitting not working for React Router

### ISSUE THREAD

**Issue by seanmcquaid** [oedotme/generouted#88]
I am in the process of setting this up on my repo and have noticed that my individual pages are not being code split. Is there a configuration I am in missing? I am following the example in the repo

**Comment by seanmcquaid** [comment]
Here is a link to my PR - https://github.com/seanmcquaid/react-template/pull/369

**Comment by seanmcquaid** [comment]
Closing as I discovered you need to use the lazy plugin!

**Comment by alexrabin** [comment]
For those that are confused like me, you have to import the Routes component from the lazy import like so:

```typescript
import { Suspense } from "react";
import { Routes } from "@generouted/react-router/lazy";
import { createRoot } from "react-dom/client";

const container = document.getElementById("root")!;
createRoot(container).render(
    <Suspense>
      <Routes />
    </Suspense>
);

```

**Comment by seanmcquaid** [comment]
Yes! Meant to comment that here, maybe this should be in the docs?

**Comment by oedotme** [comment]
@seanmcquaid Yeah definitely - the option for lazy and non-lazy default imports was introduced since [v1.12.0](https://github.com/oedotme/generouted/releases/tag/v1.12.0). I'll add it to the docs, thanks for pointing that out!
