### ISSUE TITLE
Usage within Laravel project

### ISSUE THREAD

**Issue by hizzely** [oedotme/generouted#90]
Hi! I want to use this useful library but having issues because I'm following Laravel's project structure which looked like this:
```
.
├── resources/
│   ├── js/
│   │   └── src/
│   │       ├── pages/
│   │       │   ├── _app.jsx  <- I set up a UI library here
│   │       │   └── index.jsx <- I put some hello world message here
│   │       └── main.jsx
│   └── views/
│       └── app.blade.php <- the "index.html"
├── vite.config.js
├── package.json
└── package-lock.json
```
As you can see, the files are spread between the root directory, `/resources/js/src`, and `/resources/views`.
I tried installing this library and it seems didn't find the `src/pages/_app.jsx` or the `src/pages/index.jsx` file.
Due to some constraints, I cannot separate the backend and frontend codebase. So I have to live with this structure and find a workaround.

Is it possible to configure the library to work with structure like this? Thank you!

**Comment by oedotme** [comment]
Hey @hizzely, at the moment there's only one supported structure for everything to work as expected, which is at `src/pages` in the project root.

Customizing that should be straight forward but it will need few changes in `generouted`. After the update the steps would be to 1. copy/paste a custom integration based on one of the current integrations and only change the vite glob pattern. 2. change the path of the generated router file via the vite plugin options.

I'll update this issue once it's supported and probably add a generic example with the customization steps.

Thanks!

**Comment by oedotme** [comment]
Hey @hizzely, support for the `src/pages` nested other directories is now added at [v1.13.0](https://github.com/oedotme/generouted/releases/tag/v1.13.0).

The steps would be as I described in the previous comment, you can find more details at the [custom integration example readme](https://github.com/oedotme/generouted/tree/main/examples/react-router-custom).

Hope that helps!
