### ISSUE TITLE
Unable to use the same parameter name for multiple routes

### ISSUE THREAD

**Issue by jacquesg** [oedotme/generouted#93]
Thank you for your work on this project, this was exactly what I needed.

It isn't currently possible to reuse a parameter across multiple routes, because ultimately the `id` assigned takes on the parameter name. I for example have 6 different routes that have `/[id]/` somewhere in them.

This needs to be unique as per the following error:

```
history.ts:480 Uncaught Error: Found a route id collision on id ":id".  Route id's must be globally unique within Data Router usages
    at invariant (history.ts:480:11)
    at utils.ts:371:5
    at Array.map (<anonymous>)
    at convertRoutesToDataRoutes (utils.ts:364:17)
    at utils.ts:395:38
    at Array.map (<anonymous>)
    at convertRoutesToDataRoutes (utils.ts:364:17)
    at utils.ts:395:38
    at Array.map (<anonymous>)
    at convertRoutesToDataRoutes (utils.ts:364:17)
invariant @ history.ts:480
(anonymous) @ utils.ts:371
convertRoutesToDataRoutes @ utils.ts:364
(anonymous) @ utils.ts:395
convertRoutesToDataRoutes @ utils.ts:364
(anonymous) @ utils.ts:395
convertRoutesToDataRoutes @ utils.ts:364
(anonymous) @ utils.ts:395
convertRoutesToDataRoutes @ utils.ts:364
(anonymous) @ utils.ts:395
convertRoutesToDataRoutes @ utils.ts:364
(anonymous) @ utils.ts:395
convertRoutesToDataRoutes @ utils.ts:364
createRouter @ router.ts:711
createBrowserRouter @ index.tsx:223
(anonymous) @ reactrouterv6.tsx:259
(anonymous) @ router.tsx:275
```

Here is the diff that solved my problem. Obviously this is a very ugly workaround, and was applied against the generated version in the `dist/` directory, but the gist of it is the same.

```diff
diff --git a/node_modules/@generouted/react-router/dist/chunk-KRHONMGK.js b/node_modules/@generouted/react-router/dist/chunk-KRHONMGK.js
index 44d8c37..cff7d1a 100644
--- a/node_modules/@generouted/react-router/dist/chunk-KRHONMGK.js
+++ b/node_modules/@generouted/react-router/dist/chunk-KRHONMGK.js
@@ -13,6 +13,7 @@ var generatePreservedRoutes = (files) => {
   }, {});
 };
 var generateRegularRoutes = (files, buildRoute) => {
+  let counter = 0;
   const filteredRoutes = Object.keys(files).filter((key) => !key.includes("/_") || /_layout\.(jsx|tsx)$/.test(key));
   return filteredRoutes.reduce((routes, key) => {
     const module = files[key];
@@ -36,7 +37,7 @@ var generateRegularRoutes = (files, buildRoute) => {
       if (root || node) {
         const current = root ? routes : parent.children;
         const found = current?.find((route2) => route2.path === path || route2.id === path);
-        const props = group ? route?.component ? { id: path, path: "/" } : { id: path } : { path };
+        const props = group ? route?.component ? { id: `${path}${++counter}`, path: "/" } : { id: `${path}${++counter}` } : { path };
         if (found)
           found.children ??= [];
         else
@@ -44,7 +45,7 @@ var generateRegularRoutes = (files, buildRoute) => {
         return found || current?.[insert === "unshift" ? 0 : current.length - 1];
       }
       if (layout) {
-        return Object.assign(parent, { ...route, id: parent.id || parent.path });
+        return Object.assign(parent, { ...route, id: `${parent.id || parent.path}${++counter}` });
       }
       if (leaf) {
         parent?.children?.[insert](route?.index ? route : { path, ...route });
```

**Comment by oedotme** [comment]
Hey @jacquesg thanks for sharing that!

I recall that each route id is and should be unique otherwise you'd get errors when defining the routes if I recall correctly. At the moment, each id is derived from each file path. I don't see what's causing the issue here, but I might be missing something.

Could you please provide a StackBlitz repro? You could fork [the `react-router` example](https://stackblitz.com/github.com/oedotme/generouted/tree/main/examples/react-router) and replace the `pages` directory with your pages content.

**Comment by jacquesg** [comment]
Looking at this again, I suspect `id: parent.id || parent.path` is the culprit, as it will be a duplicate.

**Comment by oedotme** [comment]
Thanks @jacquesg! I see what's going on, thanks for providing all this information.

I'll take a look into that and update you once it's resolved.

**Comment by jacquesg** [comment]
Thank you, really appreciated.

**Comment by oedotme** [comment]
Hey @jacquesg, I've pushed a fix to ensure the uniqueness of the layout ids at [v1.13.5](https://github.com/oedotme/generouted/releases/tag/v1.13.5), it's pretty much similar to what you suggested but using the full file path instead of the counter https://github.com/oedotme/generouted/commit/dd994279db0df448004980f7c89799b3868dbaac

**Comment by jacquesg** [comment]
@oedotme Thank you, this has fixed my problem!
