### ISSUE TITLE
reload page

### ISSUE THREAD

**Issue by willowloveforever** [oedotme/generouted#96]
Hello, I would like to ask what if I want to re render a component and reload the loadFn function without refreshing the page. What should I do. thanks

**Comment by oedotme** [comment]
Hey @willowloveforever, I'm not sure that's possible, it's more about Vite and the framework-specific HMR implementation. You can find more details about how it's expected to work on the [React plugin for Vite docs](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#consistent-components-exports) and [Gatsby docs](https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/#how-it-works)
