### ISSUE TITLE
Set a custom error page

### ISSUE THREAD

**Issue by hugo-instasense** [oedotme/generouted#97]
![image](https://github.com/oedotme/generouted/assets/111491022/4e3e3c60-aab7-4bbe-9ead-b51757abaa33)

How can I set a global custom error page for generouted instead of this one instead of:
```
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.
```

**Comment by hi019** [comment]
Would exporting `Catch` work? From a quick look at the code:

https://github.com/oedotme/generouted/blob/5c88344968bd270f782387cd998fcbad8c24daf7/packages/generouted/src/react-location.tsx#L18

**Comment by oedotme** [comment]
@hi019 Yes indeed, exporting a page-level `Catch` component should work but only on a page level.

Global `Catch` component support from `src/pages/_app.tsx` is now added at [v1.14.0](https://github.com/oedotme/generouted/releases/tag/v1.14.0):

```tsx
// src/pages/_app.tsx

export const Catch = () => <div>...</div>
```

cc @hugo-instasense
