### ISSUE TITLE
React router lazy error `Cannot access 'Catch' before initialization` at `_app.tsx`

### ISSUE THREAD

**Issue by Aysnine** [oedotme/generouted#98]
### Describe the Bug

I attempted to use lazy loading and cloned the react-router from the examples repository. 

Following the instructions in the documentation, I only modified the import statement in the `main.tsx` file. After saving and refreshing the page, there was no output on the webpage and the console displayed an error message `Uncaught ReferenceError: Cannot access 'Catch' before initialization`.

It seems that the error is related to the `Catch` in `_app.tsx`. After commenting it out, the page returned to normal. However, everything is normal in non-lazy mode.

### Generouted Version

1.14.0

### Your Example Website or App or Reproduction

https://stackblitz.com/edit/github-hn3rjt?file=package.json

### Steps to Reproduce the Bug or Issue

1. `main.tsx`:  `import { Routes } from "@generouted/react-router";` ->  `import { Routes } from "@generouted/react-router/lazy";`
2. page not work.
3. open console.

### Expected Behavior

The page is displaying normally.

### Screenshots or Videos

<img width="1294" alt="image" src="https://github.com/oedotme/generouted/assets/10137653/3db2fc87-7523-40fd-a50d-9b5a22a977fe">
<img width="861" alt="image" src="https://github.com/oedotme/generouted/assets/10137653/90e7f929-c71e-4b1f-8d25-35acf79bf25c">

### Platform

- OS: MacOS
- Browser: Chrome
- Browser version: 114.0

**Comment by oedotme** [comment]
Hey @Aysnine, I found that you're using the non-lazy import at `src/pages/_app.tsx`. Once I've updated its import to use the lazy one, it works just fine:
<br>

<img width="1920" alt="image" src="https://github.com/oedotme/generouted/assets/20151138/629240d9-6c53-4db3-a70c-6f0c21ff71e7">

<br>
<br>

Here's the modified [StackBlitz link](https://stackblitz.com/edit/github-hn3rjt-85bghr?file=src%2Fpages%2F_app.tsx)

Hope that helps!

**Comment by Aysnine** [comment]
Thanks ~ This has resolved my issue. I mistakenly thought that I only needed to import `lazy` in `main.tsx`.

I just noticed this repo and I believe it's one of the best file-based solutions I've been looking for. I will definitely try it out in my upcoming personal projects. Thank you for your work on this great project. 👍

**Comment by oedotme** [comment]
Hey @Aysnine, thanks for your comment and I'm very glad to hear that!

I'll probably also add a note to the docs about changing the import at `src/pages/_app.tsx` as well for it to be more clear while using or switching to the lazy routes with code-splitting.
