### ISSUE TITLE
 createRoot(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by mweel1** [oedotme/generouted#99]
### Describe the Bug

<img width="931" alt="image" src="https://github.com/oedotme/generouted/assets/77025147/3c0c86a1-66a7-42fe-b480-a8752a4b7276">

Tried 1.14.x got the same thing.

main.tsx
```
import { createRoot } from "react-dom/client";
import { Routes } from "@generouted/react-router";
// import { Routes } from '@generouted/react-router/lazy' // route-based code-splitting

const container = document.getElementById("app")!;
createRoot(container).render(<Routes />);
```

Its generating my ./router.ts file ok.

```
// Generouted, changes to this file will be overriden
/* eslint-disable */

import { components, hooks, utils } from '@generouted/react-router/client'

export type Path =
  | `/`
  | `/patient`

export type Params = {
  
}

export type ModalPath = never

export const { Link, Navigate } = components<Path, Params>()
export const { useModals, useNavigate, useParams } = hooks<Path, Params, ModalPath>()
export const { redirect } = utils<Path, Params>()
```

### Generouted Version

1.15.0

### Your Example Website or App or Reproduction

n/a

### Steps to Reproduce the Bug or Issue

Followed the documentation

### Expected Behavior

Router to fire up.

### Platform

macOS
Chrome

**Comment by mweel1** [comment]
This happened because my index.html was using id="root" instead of id="app".

This was a standard vite install, so not sure if app is the right default or not?

**Comment by oedotme** [comment]
Hey @mweel1, thanks for pointing out that. I'll probably add a note about the app/root element or update the getting started examples.
